import type { TeacherGuide } from './teacherGuides.ts'

function chapterGuide(
  title: string,
  objective: string,
  concepts: string[],
  lab: string,
  assess: string[],
): TeacherGuide {
  return {
    objectives: [objective],
    keyConcepts: concepts,
    misconceptions: [`"This topic is optional fluff — skip it."`],
    discussion: [`How does ${title} connect to the chapters before and after it?`],
    lab,
    assess,
  }
}

export const reactChapterGuides: Record<string, TeacherGuide> = {
  'react-intro': chapterGuide(
    'Why React',
    'Explain UI = f(state) and why components compose modern interfaces.',
    ['UI = f(state)', 'Components are reusable UI functions', 'State changes trigger efficient re-renders'],
    'Open the student chapter and relate f(state) to a counter or toggle demo later in the track.',
    ['What does UI = f(state) mean?', 'What does a React component return?'],
  ),
  'react-jsx-basics': chapterGuide(
    'Components & JSX',
    'Write a component that returns JSX and compose child components.',
    ['JSX compiles to React.createElement', 'PascalCase component names', 'One root element per return'],
    'Have students sketch an App component tree on paper before opening the chapter.',
    ['Why use PascalCase for components?', 'What does JSX compile to?'],
  ),
  'react-jsx-rules': chapterGuide(
    'JSX syntax rules',
    'Apply JSX rules: className, fragments, self-closing tags, and expressions.',
    ['className not class', 'Fragments <>', 'Curly braces for expressions only'],
    'Spot deliberate JSX bugs (class, missing key, inline if) on the board.',
    ['Why className instead of class?', 'Can you put an if statement directly inside JSX braces?'],
  ),
  'react-props': chapterGuide(
    'Props',
    'Describe props as read-only inputs from parent to child.',
    ['Props flow down', 'Props are immutable in the child', 'Destructure in the parameter list'],
    'Open the props lab chapter after explaining Badge/Greeting examples.',
    ['Are props mutable in the child?', 'Who owns prop values — parent or child?'],
  ),
  'react-state': chapterGuide(
    'useState',
    'Use useState and update state with the setter, never by mutation.',
    ['[value, setter] tuple', 'Functional updates', 'Immutable object/array updates'],
    'Demo setCount(c => c + 1) vs setCount(count + 1) when batching clicks.',
    ['What does useState return?', 'Why not mutate state directly?'],
  ),
  'react-events': chapterGuide(
    'Event handlers',
    'Attach onClick/onChange handlers that call state setters.',
    ['camelCase event props', 'Pass function reference not invocation', 'Synthetic events'],
    'Show the onClick={handleClick()} bug live in DevTools or a one-line example.',
    ['Why is onClick={fn()} wrong?', 'What triggers a re-render after a click?'],
  ),
  'react-lists': chapterGuide(
    'Lists & keys',
    'Render lists with map, stable keys, and immutable updates.',
    ['key helps reconciliation', 'Avoid index keys when reordering', 'Spread/map for updates'],
    'Open the todo list lab and toggle items while discussing keys.',
    ['Why use key={todo.id}?', 'Why not todos.push then setTodos(todos)?'],
  ),
  'react-effects': chapterGuide(
    'useEffect',
    'Run side effects after render and control dependencies.',
    ['Effects after paint', 'Dependency array', 'Cleanup functions'],
    'Trace document.title or a fake fetch example with different dependency arrays.',
    ['What does useEffect([], []) do?', 'When do you need a cleanup return?'],
  ),
  'react-store-lift': chapterGuide(
    'Lifting state',
    'Recognize prop drilling and lift state to a common ancestor.',
    ['Prop drilling', 'Lift to nearest common parent', 'Context/store when depth grows'],
    'Draw a three-level tree and mark where shared cart state should live.',
    ['What is prop drilling?', 'When should you lift state?'],
  ),
  'react-store-context': chapterGuide(
    'Context',
    'Provide shared values with Context and useContext.',
    ['Provider at subtree root', 'useContext in descendants', 'Avoid fast-updating Context values'],
    'Use the profile demo — edit name/role and watch Header + Sidebar sync.',
    ['When is Context a good fit?', 'Why avoid high-frequency updates in Context?'],
  ),
  'react-store-external': chapterGuide(
    'External stores',
    'Compare Zustand/Redux to Context for shared client state.',
    ['Subscribe to external store', 'Redux actions/reducers', 'Zustand minimal API'],
    'Run the cart store demo; add items and relate to subscribe pattern.',
    ['When prefer a store over Context?', 'What problem does Redux solve?'],
  ),
  'react-lab-counter': chapterGuide(
    'Counter lab',
    'Operate the live counter and relate clicks to useState.',
    ['setCount schedules re-render', 'Functional updates', 'State persists across prop changes'],
    'Students increment/decrement and predict render count.',
    ['What happens on each button click?', 'Why use setCount(c => c + 1)?'],
  ),
  'react-lab-props': chapterGuide(
    'Props lab',
    'Edit parent inputs and observe child re-render without child state.',
    ['Parent owns changing values', 'Child receives new props', 'No state in Greeting'],
    'Change name/role fields and confirm counter lab state would be independent.',
    ['Who passes props to Greeting?', 'Does Greeting store its own copy of name?'],
  ),
  'react-lab-lists': chapterGuide(
    'Todo list lab',
    'Add and toggle todos with immutable list updates.',
    ['map for toggle', 'spread for add', 'stable keys'],
    'Add two todos, toggle one, delete mentally — predict which DOM nodes reconcile.',
    ['How do you toggle one todo immutably?', 'Why key={todo.id}?'],
  ),
  'react-hood-vdom': chapterGuide(
    'Virtual DOM',
    'Explain reconciliation and minimal DOM updates.',
    ['Virtual DOM tree', 'Diffing', 'Reconciliation'],
    'Contrast manual DOM APIs vs declarative re-render mental model.',
    ['What is reconciliation?', 'Why re-render whole subtrees safely?'],
  ),
  'react-hood-hooks': chapterGuide(
    'Rules of hooks',
    'State why hooks must be called unconditionally at top level.',
    ['Call order matters', 'No hooks in loops/conditions', 'Custom hooks follow same rules'],
    'Show a broken conditional useState example and the runtime error.',
    ['Why no hooks inside if blocks?', 'What does React use call order for?'],
  ),
  'react-hood-stack': chapterGuide(
    'React ecosystem',
    'Place React alongside router, data fetching, TypeScript, and FastAPI.',
    ['React is view layer', 'TanStack Query for server state', 'Vite for bundling'],
    'Whiteboard a React + FastAPI + Postgres diagram from this course.',
    ['Is React a full framework?', 'Where does server state often live?'],
  ),
}

export const fastapiChapterGuides: Record<string, TeacherGuide> = {
  'fastapi-intro': chapterGuide(
    'Why FastAPI',
    'Motivate FastAPI with validation, OpenAPI, and Python type hints.',
    ['Routes + models + auto docs', 'Built on Starlette/Pydantic', 'Pairs with React frontend'],
    'Connect to the APIs & REST chapter before opening student lab.',
    ['What does FastAPI generate automatically?', 'How does it reduce boilerplate?'],
  ),
  'fastapi-routes-basics': chapterGuide(
    'GET routes',
    'Define GET handlers returning JSON and handle 404 shapes.',
    ['@app.get decorator', 'dict/list auto JSON', 'Path operations'],
    'Run Route handlers snippet; compare get_user(1) vs get_user(99).',
    ['What does @app.get register?', 'How are Python dicts returned to clients?'],
  ),
  'fastapi-routes-crud': chapterGuide(
    'CRUD routes',
    'Map POST/PUT/DELETE to create, update, delete with correct status codes.',
    ['201 on create', '204 on delete', 'Idempotency of PUT/DELETE'],
    'List which verbs are idempotent from the APIs lesson.',
    ['Which status for create?', 'Is POST idempotent by default?'],
  ),
  'fastapi-models-request': chapterGuide(
    'Request models',
    'Validate JSON bodies with Pydantic before handlers run.',
    ['BaseModel fields', '422 on validation failure', 'model_dump()'],
    'Run Pydantic validation snippet with valid/invalid bodies.',
    ['What status for invalid body?', 'When does validation run?'],
  ),
  'fastapi-models-response': chapterGuide(
    'Response models',
    'Filter/document responses with response_model.',
    ['response_model in decorator', 'OpenAPI documents output', '201/204 patterns'],
    'Show UserOut example and discuss hidden fields.',
    ['What does response_model do?', 'Why declare response shapes?'],
  ),
  'fastapi-params-path': chapterGuide(
    'Path parameters',
    'Bind URL segments to typed parameters.',
    ['/{name} in path', 'Type validation before handler', '422 on bad types'],
    'Give examples of path vs query confusion on the board.',
    ['Where does user_id come from in /users/{user_id}?', 'What if user_id is not an int?'],
  ),
  'fastapi-params-query': chapterGuide(
    'Query parameters',
    'Parse ?q=&limit= from function defaults.',
    ['Defaults imply query params', 'Pagination skip/limit', 'Optional filters'],
    'Run search_items snippet with different q/limit/skip.',
    ['How does FastAPI know a param is query vs path?', 'What does limit=10 mean?'],
  ),
  'fastapi-params-body': chapterGuide(
    'Request body',
    'Combine body model with path and query in one signature.',
    ['One body model per handler', 'Body + query together', 'POST JSON mapping'],
    'Sketch a create_user(body, active: bool = True) signature.',
    ['Can you have two body models?', 'Where does active=true come from?'],
  ),
  'fastapi-deps-database': chapterGuide(
    'Database dependencies',
    'Inject DB sessions with Depends and override in tests.',
    ['Depends(get_db)', 'yield for cleanup', 'Override in tests'],
    'Run DI snippet; discuss swapping get_db in pytest.',
    ['What does Depends(get_db) do?', 'Why yield in get_db?'],
  ),
  'fastapi-deps-auth': chapterGuide(
    'Auth dependencies',
    'Validate bearer tokens and return current user.',
    ['HTTPException 401', 'Bearer scheme', 'Depends(get_current_user)'],
    'Run auth dependency snippet with valid/invalid tokens.',
    ['What status for missing token?', 'Where should auth run — handler or dependency?'],
  ),
  'fastapi-errors': chapterGuide(
    'HTTPException',
    'Return structured errors with correct status codes.',
    ['raise HTTPException', '404 not found', '204 no content'],
    'Run delete_user snippet for success vs failure.',
    ['When to raise HTTPException?', 'What status for missing resource?'],
  ),
  'fastapi-hood-asgi': chapterGuide(
    'ASGI & async',
    'Use async def when awaiting I/O.',
    ['ASGI server interface', 'async def handlers', 'await DB/HTTP'],
    'Run async handler snippet; contrast blocking def vs await.',
    ['When use async def?', 'What happens while awaiting I/O?'],
  ),
  'fastapi-hood-openapi': chapterGuide(
    'OpenAPI docs',
    'Use /docs and type hints as living documentation.',
    ['Swagger UI at /docs', 'Schema from hints', 'Share with frontend teams'],
    'If running locally, open /docs; otherwise walk through generated schema concept.',
    ['Where are interactive docs served?', 'What generates the schema?'],
  ),
  'fastapi-hood-cors': chapterGuide(
    'CORS',
    'Configure CORSMiddleware for React on another origin.',
    ['Cross-origin browser policy', 'Access-Control-Allow-Origin', 'Vite port 5173 example'],
    'Run CORS simulation snippet; relate to React fetch example.',
    ['Why does localhost:5173 need CORS for :8000?', 'Who must send CORS headers?'],
  ),
  'fastapi-hood-stack': chapterGuide(
    'Full-stack stack',
    'Connect React UI, FastAPI API, and databases.',
    ['Validate at API edge', 'DB is source of truth', 'Course persistence chapters'],
    'Diagram React → FastAPI → PostgreSQL/MongoDB using prior lessons.',
    ['Where does validation happen?', 'What stores authoritative state?'],
  ),
}

export const databasesChapterGuides: Record<string, TeacherGuide> = {
  'databases-intro': chapterGuide('Why databases', 'Explain durable storage vs RAM.', ['Persistence', 'Source of truth', 'Beyond plain files'], 'Contrast in-memory dict vs restarted process losing data.', ['Why not keep everything in RAM?', 'What is the source of truth?']),
  'databases-architecture': chapterGuide('Architecture', 'Map app → driver → engine → disk.', ['Embedded vs client-server', 'Drivers/connectors', 'Connection pools'], 'Draw SQLite in-process vs Postgres server diagram.', ['When use embedded SQLite?', 'What does a driver do?']),
  'databases-models': chapterGuide('Data models', 'Survey relational, document, key-value, graph.', ['Table vs document vs key', 'Polyglot persistence', 'Access patterns'], 'Give one example query each family handles well.', ['When JOIN-heavy SQL?', 'When documents fit better?']),
  'databases-acid': chapterGuide('ACID', 'Teach transactions with transfer example.', ['Atomicity', 'Isolation', 'Durability'], 'Walk through debit+credit commit/rollback story.', ['What does atomic mean?', 'When do you need a transaction?']),
  'databases-schemas': chapterGuide('Schema design', 'Normalization, constraints, migrations.', ['Normalize first', 'Foreign keys', 'Migration scripts'], 'Sketch customers/orders ERD before SQL module.', ['What does normalization reduce?', 'Why migrations?']),
  'databases-choosing': chapterGuide('SQL vs Mongo', 'Decision framework before deep dives.', ['Joins vs embed', 'Schema stability', 'Redis as cache'], 'Poll class: ecommerce orders — SQL or Mongo? Discuss.', ['Default for structured APIs?', 'When Mongo wins?']),
  'databases-hood': chapterGuide('Production basics', 'Replication, backups, sharding overview.', ['Replica sets', 'Test restores', 'Index trade-offs'], 'Emphasize untested backups are a risk.', ['What does replication help?', 'When shard?']),
}

export const sqlChapterGuides: Record<string, TeacherGuide> = {
  'sql-intro': chapterGuide('Why SQL', 'Explain declarative SQL over relational tables.', ['Tables and rows', 'Declarative queries', 'Portable across engines'], 'Relate to the sample customers/orders schema used later.', ['What is declarative SQL?', 'Where does data live in a relational DB?']),
  'sql-tables': chapterGuide('Tables & queries', 'Write SELECT, WHERE, ORDER BY, LIMIT.', ['SELECT/FROM/WHERE', 'ORDER BY and LIMIT', 'JOIN and GROUP BY intro'], 'Sketch a query on the board before opening the playground.', ['Which clause filters rows?', 'What does JOIN combine?']),
  'sql-schema': chapterGuide('Schema & keys', 'Define primary and foreign keys and relationships.', ['Primary key', 'Foreign key', 'Normalization trade-offs'], 'Draw customers ↔ orders ERD.', ['What does a foreign key enforce?', 'When denormalize?']),
  'sql-writes': chapterGuide('SQL writes', 'Use INSERT, UPDATE, DELETE with WHERE and transactions.', ['INSERT/UPDATE/DELETE', 'WHERE on writes', 'Transactions'], 'Show an unqualified DELETE caution tale.', ['Why use WHERE on UPDATE?', 'Why transactions for transfers?']),
  'sql-advanced': chapterGuide('Advanced SQL', 'Compare JOIN types, HAVING, and subqueries.', ['INNER vs LEFT JOIN', 'HAVING vs WHERE', 'Subqueries'], 'Run LEFT JOIN sample in playground after theory.', ['What does LEFT JOIN keep?', 'HAVING filters what?']),
  'sql-conn-sqlite': chapterGuide('SQLite', 'Connect with sqlite3 and ? placeholders.', ['sqlite3 module', ':memory: vs file', 'Parameterized queries'], 'Run Connect & query snippet.', ['Why ? placeholders?', 'When use SQLite?']),
  'sql-conn-postgres': chapterGuide('Postgres drivers', 'Use psycopg2/asyncpg and DSN strings.', ['DSN format', '%s placeholders', 'Server vs embedded'], 'Run Postgres-style connector snippet.', ['What is a DSN?', 'psycopg2 connects to what?']),
  'sql-conn-pool': chapterGuide('Connection pools', 'Reuse connections with acquire/release.', ['Pool exhaustion', 'Warm connections', 'Release after use'], 'Exhaust the pool in the snippet.', ['Why pools in web apps?', 'What happens when pool is empty?']),
  'sql-conn-orm': chapterGuide('SQLAlchemy ORM', 'Map classes to tables; know ORM trade-offs.', ['ORM generates SQL', 'Session API', 'Raw SQL for hot paths'], 'Run ORM-style query snippet; discuss when to drop to SQL.', ['What does an ORM do?', 'When prefer raw SQL?']),
  'sql-playground': chapterGuide('SQL playground', 'Run live SQLite queries on sample data.', ['Real SQLite in browser', 'Joins and aggregates', 'Writes change data'], 'Students run LEFT JOIN and INSERT samples.', ['How to find customers with zero orders?', 'What does HAVING filter?']),
  'sql-labs': chapterGuide('Python SQL labs', 'Practice sqlite3 patterns in Python.', ['Parameterization', 'JOIN in Python', 'Injection safety'], 'Run Parameterized query with malicious-looking input.', ['How do parameters stop injection?', 'Name the JOIN snippet output.']),
  'sql-hood': chapterGuide('SQL internals', 'Explain indexes, planners, and injection.', ['B-tree indexes', 'EXPLAIN plans', 'Never concatenate user input'], 'Contrast string-built query vs parameterized.', ['Why indexes help?', 'What does EXPLAIN show?']),
}

export const mongodbChapterGuides: Record<string, TeacherGuide> = {
  'mongodb-intro': chapterGuide('Why MongoDB', 'Contrast documents with relational tables.', ['Document model', 'Flexible schema', 'Embed vs reference'], 'Compare one order document vs normalized SQL tables.', ['What is a document?', 'When pick MongoDB over SQL?']),
  'mongodb-documents': chapterGuide('Documents', 'Describe collections, _id, and flexible fields.', ['_id primary key', 'Embedded arrays', 'References'], 'Run Documents as dicts snippet.', ['What is a collection?', 'Can documents differ in shape?']),
  'mongodb-queries': chapterGuide('Queries', 'Write find filters with operators.', ['Equality filters', '$gt and $in', 'JSON query syntax'], 'Filter London orders then amount > 100.', ['What does $gt mean?', 'How is find different from SQL WHERE?']),
  'mongodb-writes': chapterGuide('Writes', 'Use insertOne, updateMany, deleteMany with $set.', ['insertOne', 'updateMany + $set', 'Schema discipline'], 'Discuss typo fields without validation.', ['What does $set do?', 'Why schema discipline still matters?']),
  'mongodb-aggregation': chapterGuide('Aggregation', 'Build pipelines with $match, $group, $sort.', ['Pipeline stages', '$group + $sum', 'Like SQL GROUP BY'], 'Run Group & sum snippet; mirror in playground.', ['What is $group for?', 'First stage you usually use?']),
  'mongodb-conn-pymongo': chapterGuide('PyMongo', 'Use MongoClient and collection methods.', ['MongoClient', 'find/insert_one', 'Sync driver'], 'Insert and find_one in PyMongo snippet.', ['What does insert_one return?', 'How pick database?']),
  'mongodb-conn-uri': chapterGuide('MongoDB URI', 'Parse mongodb+srv connection strings.', ['Credentials in URI', 'retryWrites', 'Never commit secrets'], 'Parse sample Atlas URI in snippet.', ['What does mongodb+srv imply?', 'Where put credentials?']),
  'mongodb-conn-motor': chapterGuide('Motor', 'Await async database calls.', ['Motor wraps PyMongo', 'asyncio integration', 'FastAPI pairing'], 'Run Motor async snippet; tie to FastAPI lesson.', ['Why Motor in FastAPI?', 'What happens during await?']),
  'mongodb-conn-odm': chapterGuide('ODMs', 'Use Beanie/MongoEngine for typed documents.', ['ODM vs raw driver', 'Pydantic validation', 'When ODM helps'], 'Walk through Beanie Order model example.', ['When use ODM?', 'ODM vs PyMongo ad-hoc queries?']),
  'mongodb-playground': chapterGuide('Mongo playground', 'Run shell commands on in-memory docs.', ['find and aggregate', 'insert/update', 'Compare to SQL JOIN'], 'Aggregate revenue then insert a document.', ['How add $limit stage?', 'Embed vs JOIN mentally?']),
  'mongodb-labs': chapterGuide('Python labs', 'Filter and aggregate without a server.', ['Dict documents', 'Operator simulation', 'PyMongo patterns'], 'Extend Filter documents for $in.', ['How filter amount > 100?', 'What does aggregation compute?']),
  'mongodb-hood': chapterGuide('MongoDB scale', 'Choose embed vs reference; indexes and sharding.', ['Embed vs reference', 'Indexes on filter fields', 'Sharding for scale'], 'Whiteboard embed order lines vs customer reference.', ['When embed vs reference?', 'What does sharding do?']),
}
