import type { TeacherGuide } from './teacherGuides.ts'

function chapterGuide(
  title: string,
  objective: string,
  concepts: string[],
  lab: string,
  assess: string[],
): TeacherGuide {
  return {
    objectives: [objective],
    keyConcepts: concepts,
    misconceptions: [`"This topic is optional fluff — skip it."`],
    discussion: [`How does ${title} connect to the chapters before and after it?`],
    lab,
    assess,
  }
}

export const reactChapterGuides: Record<string, TeacherGuide> = {
  'react-intro': chapterGuide(
    'Why React',
    'Explain UI = f(state) and why components compose modern interfaces.',
    ['UI = f(state)', 'Components are reusable UI functions', 'State changes trigger efficient re-renders'],
    'Open the student chapter and relate f(state) to a counter or toggle demo later in the track.',
    ['What does UI = f(state) mean?', 'What does a React component return?'],
  ),
  'react-jsx-basics': chapterGuide(
    'Components & JSX',
    'Write a component that returns JSX and compose child components.',
    ['JSX compiles to React.createElement', 'PascalCase component names', 'One root element per return'],
    'Have students sketch an App component tree on paper before opening the chapter.',
    ['Why use PascalCase for components?', 'What does JSX compile to?'],
  ),
  'react-jsx-rules': chapterGuide(
    'JSX syntax rules',
    'Apply JSX rules: className, fragments, self-closing tags, and expressions.',
    ['className not class', 'Fragments <>', 'Curly braces for expressions only'],
    'Spot deliberate JSX bugs (class, missing key, inline if) on the board.',
    ['Why className instead of class?', 'Can you put an if statement directly inside JSX braces?'],
  ),
  'react-props': chapterGuide(
    'Props',
    'Describe props as read-only inputs from parent to child.',
    ['Props flow down', 'Props are immutable in the child', 'Destructure in the parameter list'],
    'Open the props lab chapter after explaining Badge/Greeting examples.',
    ['Are props mutable in the child?', 'Who owns prop values — parent or child?'],
  ),
  'react-state': chapterGuide(
    'useState',
    'Use useState and update state with the setter, never by mutation.',
    ['[value, setter] tuple', 'Functional updates', 'Immutable object/array updates'],
    'Demo setCount(c => c + 1) vs setCount(count + 1) when batching clicks.',
    ['What does useState return?', 'Why not mutate state directly?'],
  ),
  'react-events': chapterGuide(
    'Event handlers',
    'Attach onClick/onChange handlers that call state setters.',
    ['camelCase event props', 'Pass function reference not invocation', 'Synthetic events'],
    'Show the onClick={handleClick()} bug live in DevTools or a one-line example.',
    ['Why is onClick={fn()} wrong?', 'What triggers a re-render after a click?'],
  ),
  'react-lists': chapterGuide(
    'Lists & keys',
    'Render lists with map, stable keys, and immutable updates.',
    ['key helps reconciliation', 'Avoid index keys when reordering', 'Spread/map for updates'],
    'Open the todo list lab and toggle items while discussing keys.',
    ['Why use key={todo.id}?', 'Why not todos.push then setTodos(todos)?'],
  ),
  'react-effects': chapterGuide(
    'useEffect',
    'Run side effects after render and control dependencies.',
    ['Effects after paint', 'Dependency array', 'Cleanup functions'],
    'Trace document.title or a fake fetch example with different dependency arrays.',
    ['What does useEffect([], []) do?', 'When do you need a cleanup return?'],
  ),
  'react-store-lift': chapterGuide(
    'Lifting state',
    'Recognize prop drilling and lift state to a common ancestor.',
    ['Prop drilling', 'Lift to nearest common parent', 'Colocation first', 'Context/store when depth grows'],
    'Run lift demo, then prop drilling viz — edit user name and compare render badges on each layer.',
    ['What is prop drilling?', 'When should you lift state?', 'When is lifting not enough?'],
  ),
  'react-store-context': chapterGuide(
    'Context',
    'Provide shared values with Context, custom hooks, and stable Provider values.',
    ['Provider at subtree root', 'useContext / useUser()', 'Memoize value', 'Avoid fast-updating Context'],
    'Profile demo + theme toggle + re-render trap — increment count and watch unrelated consumers re-render.',
    ['When is Context a good fit?', 'Why memoize Provider value?', 'Why avoid high-frequency Context?'],
  ),
  'react-store-patterns': chapterGuide(
    'Context patterns',
    'Combine Context with useReducer and split state/dispatch providers.',
    ['Context + useReducer', 'Split state vs dispatch', 'Compound providers', 'use-context-selector'],
    'Todo reducer demo — add/toggle todos; discuss which components re-render on toggle.',
    ['Why split dispatch context?', 'When does Context + reducer become too much?'],
  ),
  'react-store-external': chapterGuide(
    'External stores',
    'Compare Zustand/Redux, selectors, and unidirectional Redux flow.',
    ['Subscribe with selectors', 'Redux actions/reducers', 'Zustand create()', 'TanStack Query for server data'],
    'Cart store + selector demo + Redux flow animation; relate to useSyncExternalStore.',
    ['When prefer a store over Context?', 'What does a selector optimize?', 'Where does API data belong?'],
  ),
  'react-store-choosing': chapterGuide(
    'Choosing state',
    'Pick local vs lift vs Context vs store vs server cache.',
    ['Client vs server state', 'URL state', 'Smell tests for drilling/re-renders', 'Simplest tool first'],
    'State chooser quiz — discuss each scenario before revealing answer.',
    ['Where does theme belong?', 'Where does GET /api data belong?', 'When reach for Redux/Zustand?'],
  ),
  'react-lab-counter': chapterGuide(
    'Counter lab',
    'Operate the live counter and relate clicks to useState.',
    ['setCount schedules re-render', 'Functional updates', 'State persists across prop changes'],
    'Students increment/decrement and predict render count.',
    ['What happens on each button click?', 'Why use setCount(c => c + 1)?'],
  ),
  'react-lab-props': chapterGuide(
    'Props lab',
    'Edit parent inputs and observe child re-render without child state.',
    ['Parent owns changing values', 'Child receives new props', 'No state in Greeting'],
    'Change name/role fields and confirm counter lab state would be independent.',
    ['Who passes props to Greeting?', 'Does Greeting store its own copy of name?'],
  ),
  'react-lab-lists': chapterGuide(
    'Todo list lab',
    'Add and toggle todos with immutable list updates.',
    ['map for toggle', 'spread for add', 'stable keys'],
    'Add two todos, toggle one, delete mentally — predict which DOM nodes reconcile.',
    ['How do you toggle one todo immutably?', 'Why key={todo.id}?'],
  ),
  'react-hood-vdom': chapterGuide(
    'Virtual DOM',
    'Explain render → reconcile → commit and why keys matter.',
    ['Element tree vs DOM', 'Diffing & commit', 'Stable keys', 'React.memo', 'Fiber scheduling'],
    'Key demo: check boxes, reverse list — contrast index vs id keys. Run pipeline animation.',
    ['What is reconciliation?', 'Why does index key break on reorder?', 'What does React.memo do?'],
  ),
  'react-hood-hooks': chapterGuide(
    'Rules of hooks',
    'Teach hook slots, call order, custom hooks, and eslint enforcement.',
    ['Top-level only', 'Same order every render', 'Custom hooks named use*', 'No hooks after early return'],
    'Five-scenario demo + slot diagram — toggle conditional hook and predict slot shift.',
    ['Why no hooks inside if blocks?', 'What does React use call order for?', 'Can custom hooks call useState?'],
  ),
  'react-hood-stack': chapterGuide(
    'React ecosystem',
    'Map Vite, Router, Query, client stores, FastAPI, and SPA vs SSR.',
    ['React is view layer', 'TanStack Query for server state', 'Vite for bundling', 'FastAPI for JSON API'],
    'Expanded ecosystem map + full-stack request flow animation + SPA vs SSR compare.',
    ['Is React a full framework?', 'Where does API data live?', 'What does Vite do in dev?'],
  ),
}

export const fastapiChapterGuides: Record<string, TeacherGuide> = {
  'fastapi-intro': chapterGuide(
    'Why FastAPI',
    'Motivate FastAPI with validation, OpenAPI, and Python type hints.',
    ['Routes + models + auto docs', 'Built on Starlette/Pydantic', 'Pairs with React frontend'],
    'Connect to the APIs & REST chapter before opening student lab.',
    ['What does FastAPI generate automatically?', 'How does it reduce boilerplate?'],
  ),
  'fastapi-routes-basics': chapterGuide(
    'GET routes',
    'Define GET handlers returning JSON and handle 404 shapes.',
    ['@app.get decorator', 'dict/list auto JSON', 'Path operations'],
    'Run Route handlers snippet; compare get_user(1) vs get_user(99).',
    ['What does @app.get register?', 'How are Python dicts returned to clients?'],
  ),
  'fastapi-routes-crud': chapterGuide(
    'CRUD routes',
    'Map POST/PUT/DELETE to create, update, delete with correct status codes.',
    ['201 on create', '204 on delete', 'Idempotency of PUT/DELETE'],
    'List which verbs are idempotent from the APIs lesson.',
    ['Which status for create?', 'Is POST idempotent by default?'],
  ),
  'fastapi-models-request': chapterGuide(
    'Request models',
    'Validate JSON bodies with Pydantic before handlers run.',
    ['BaseModel fields', '422 on validation failure', 'model_dump()'],
    'Run Pydantic validation snippet with valid/invalid bodies.',
    ['What status for invalid body?', 'When does validation run?'],
  ),
  'fastapi-models-response': chapterGuide(
    'Response models',
    'Filter/document responses with response_model.',
    ['response_model in decorator', 'OpenAPI documents output', '201/204 patterns'],
    'Show UserOut example and discuss hidden fields.',
    ['What does response_model do?', 'Why declare response shapes?'],
  ),
  'fastapi-params-path': chapterGuide(
    'Path parameters',
    'Bind URL segments to typed parameters.',
    ['/{name} in path', 'Type validation before handler', '422 on bad types'],
    'Give examples of path vs query confusion on the board.',
    ['Where does user_id come from in /users/{user_id}?', 'What if user_id is not an int?'],
  ),
  'fastapi-params-query': chapterGuide(
    'Query parameters',
    'Parse ?q=&limit= from function defaults.',
    ['Defaults imply query params', 'Pagination skip/limit', 'Optional filters'],
    'Run search_items snippet with different q/limit/skip.',
    ['How does FastAPI know a param is query vs path?', 'What does limit=10 mean?'],
  ),
  'fastapi-params-body': chapterGuide(
    'Request body',
    'Combine body model with path and query in one signature.',
    ['One body model per handler', 'Body + query together', 'POST JSON mapping'],
    'Sketch a create_user(body, active: bool = True) signature.',
    ['Can you have two body models?', 'Where does active=true come from?'],
  ),
  'fastapi-deps-database': chapterGuide(
    'Database dependencies',
    'Inject DB sessions with Depends and override in tests.',
    ['Depends(get_db)', 'yield for cleanup', 'Override in tests'],
    'Run DI snippet; discuss swapping get_db in pytest.',
    ['What does Depends(get_db) do?', 'Why yield in get_db?'],
  ),
  'fastapi-deps-auth': chapterGuide(
    'Auth dependencies',
    'Validate bearer tokens and return current user.',
    ['HTTPException 401', 'Bearer scheme', 'Depends(get_current_user)'],
    'Run auth dependency snippet with valid/invalid tokens.',
    ['What status for missing token?', 'Where should auth run — handler or dependency?'],
  ),
  'fastapi-errors': chapterGuide(
    'HTTPException',
    'Return structured errors with correct status codes.',
    ['raise HTTPException', '404 not found', '204 no content'],
    'Run delete_user snippet for success vs failure.',
    ['When to raise HTTPException?', 'What status for missing resource?'],
  ),
  'fastapi-hood-asgi': chapterGuide(
    'ASGI & async',
    'Use async def when awaiting I/O.',
    ['ASGI server interface', 'async def handlers', 'await DB/HTTP'],
    'Run async handler snippet; contrast blocking def vs await.',
    ['When use async def?', 'What happens while awaiting I/O?'],
  ),
  'fastapi-hood-openapi': chapterGuide(
    'OpenAPI docs',
    'Use /docs and type hints as living documentation.',
    ['Swagger UI at /docs', 'Schema from hints', 'Share with frontend teams'],
    'If running locally, open /docs; otherwise walk through generated schema concept.',
    ['Where are interactive docs served?', 'What generates the schema?'],
  ),
  'fastapi-hood-cors': chapterGuide(
    'CORS',
    'Configure CORSMiddleware for React on another origin.',
    ['Cross-origin browser policy', 'Access-Control-Allow-Origin', 'Vite port 5173 example'],
    'Run CORS simulation snippet; relate to React fetch example.',
    ['Why does localhost:5173 need CORS for :8000?', 'Who must send CORS headers?'],
  ),
  'fastapi-hood-stack': chapterGuide(
    'Full-stack stack',
    'Connect React UI, FastAPI API, and databases.',
    ['Validate at API edge', 'DB is source of truth', 'Course persistence chapters'],
    'Diagram React → FastAPI → PostgreSQL/MongoDB using prior lessons.',
    ['Where does validation happen?', 'What stores authoritative state?'],
  ),
}

export const databasesChapterGuides: Record<string, TeacherGuide> = {
  'databases-intro': chapterGuide('Why databases', 'Explain durable storage vs RAM.', ['Persistence', 'Source of truth', 'Beyond plain files'], 'Contrast in-memory dict vs restarted process losing data.', ['Why not keep everything in RAM?', 'What is the source of truth?']),
  'databases-architecture': chapterGuide('Architecture', 'Map app → driver → engine → disk.', ['Embedded vs client-server', 'Drivers/connectors', 'Connection pools'], 'Draw SQLite in-process vs Postgres server diagram.', ['When use embedded SQLite?', 'What does a driver do?']),
  'databases-models': chapterGuide('Data models', 'Survey relational, document, key-value, graph.', ['Table vs document vs key', 'Polyglot persistence', 'Access patterns'], 'Give one example query each family handles well.', ['When JOIN-heavy SQL?', 'When documents fit better?']),
  'databases-acid': chapterGuide('ACID', 'Teach transactions with transfer example.', ['Atomicity', 'Isolation', 'Durability'], 'Walk through debit+credit commit/rollback story.', ['What does atomic mean?', 'When do you need a transaction?']),
  'databases-schemas': chapterGuide('Schema design', 'Normalization, constraints, migrations.', ['Normalize first', 'Foreign keys', 'Migration scripts'], 'Toggle normalized vs denormalized in NormalizationSim; rename customer and discuss update anomalies.', ['What does normalization reduce?', 'Why migrations?']),
  'databases-choosing': chapterGuide('SQL vs Mongo', 'Decision framework before deep dives.', ['Joins vs embed', 'Schema stability', 'Redis as cache'], 'Poll class: ecommerce orders — SQL or Mongo? Discuss.', ['Default for structured APIs?', 'When Mongo wins?']),
  'databases-hood': chapterGuide('Production basics', 'Replication, backups, sharding overview.', ['Replica sets', 'Test restores', 'Index trade-offs'], 'Emphasize untested backups are a risk.', ['What does replication help?', 'When shard?']),
}

export const cssChapterGuides: Record<string, TeacherGuide> = {
  'css-intro': chapterGuide(
    'Why CSS feels hard',
    'Explain declarative CSS, cascade, and why DevTools beat guessing.',
    ['Cascade and inheritance', 'Every element is a box', 'Browser default styles', 'Computed styles in DevTools'],
    'Have students inspect this app’s sidebar in DevTools and find which rule sets width and overflow.',
    ['What does the cascade resolve?', 'First step when a style “does not apply”?'],
  ),
  'css-box-model': chapterGuide(
    'The box model',
    'Diagram content, padding, border, margin, and box-sizing.',
    ['Four layers of every element', 'content-box vs border-box', 'Margin collapse'],
    'Run the box model lab; toggle content-box with padding and watch outer width exceed 200px.',
    ['Where does margin sit?', 'What does border-box include in width?'],
  ),
  'css-layout': chapterGuide(
    'Flex & Grid',
    'Contrast one-dimensional flex with two-dimensional grid page shells.',
    ['display: flex on parent', 'justify-content and align-items', 'grid-template-columns and fr'],
    'Center a row in FlexPlayground without margin: auto; relate grid columns to this app’s sidebar layout.',
    ['Flexbox is best for what dimension?', 'What does 1fr mean in grid?'],
  ),
  'css-position': chapterGuide(
    'Position & stacking',
    'Teach static/relative/absolute/fixed/sticky and z-index stacking contexts.',
    ['Relative parent + absolute child', 'fixed vs viewport', 'z-index needs positioned element'],
    'Move the badge from absolute to fixed; discuss dropdown clipping from overflow: hidden parents.',
    ['Absolute is positioned relative to what?', 'Why might z-index appear ignored?'],
  ),
  'css-overflow': chapterGuide(
    'Overflow & scrolling',
    'Compare visible, hidden, scroll, and auto; link to sidebar scroll.',
    ['Scroll containers', 'hidden clips descendants', 'auto vs scroll'],
    'Overflow lab with tall content; point at this course nav using overflow-y: auto.',
    ['When does auto show scrollbars?', 'How can overflow: hidden break dropdowns?'],
  ),
  'css-themes': chapterGuide(
    'Themes & CSS variables',
    'Define tokens with custom properties and swap palettes via data-theme.',
    ['--token syntax and var()', 'Semantic tokens vs raw hex', 'data-theme on html'],
    'ThemePlayground presets; open Theme dropdown in app sidebar to show the same mechanism.',
    ['How are CSS variables declared?', 'Why semantic tokens beat hard-coded colors?'],
  ),
  'css-cascade': chapterGuide(
    'Cascade & specificity',
    'Read specificity scores and when inheritance applies.',
    ['id vs class vs element weight', 'Source order tie-break', '!important as last resort'],
    'Write two conflicting rules on the board; have students predict the winner before revealing specificity.',
    ['Which selector usually wins: #id or .class?', 'Does margin inherit from parent?'],
  ),
  'css-hacks': chapterGuide(
    'Hacks vs proper fixes',
    'Map float clears, magic margins, and z-index wars to flex/grid/border-box fixes.',
    ['Float layout is legacy', 'Stacking context over huge z-index', 'DevTools debugging checklist'],
    'Walk the Under the hood checklist on a real misaligned element in DevTools layout overlay.',
    ['Modern replacement for float columns?', 'First tool when CSS looks wrong?'],
  ),
}

export const webChapterGuides: Record<string, TeacherGuide> = {
  'web-reverse-proxy': chapterGuide('Reverse proxy', 'Contrast forward vs reverse proxies; nginx at the edge.', ['Reverse vs forward', 'TLS termination', 'upstream'], 'Run ReverseProxySim — animate HTTPS → nginx → upstream; click diagram nodes.', ['Where does nginx sit?', 'Why terminate TLS at edge?']),
  'web-nginx-routing': chapterGuide('nginx routing', 'Teach location blocks and proxy_pass.', ['Longest prefix', 'upstream pools', 'path routing'], 'Use RouteSim with /api and /admin paths; highlight nodes in the Mermaid diagram.', ['What wins: / or /api/?', 'What does proxy_pass do?']),
  'web-api-gateway': chapterGuide('API gateway', 'Compare gateway vs plain reverse proxy.', ['API keys', 'central auth', 'quotas'], 'ApiGatewaySim with valid vs invalid keys; discuss 401 before backend.', ['Gateway vs nginx?', 'Why centralize auth?']),
  'web-rate-limiting': chapterGuide('Rate limiting', 'Token bucket and 429 responses.', ['429 Too Many Requests', 'per-key limits', 'Redis counters'], 'Burst the RateLimitSim; watch diagram route to 429 vs 200.', ['When return 429?', 'Per-IP vs per-key?']),
  'web-edge-stack': chapterGuide('Edge stack', 'Walk full production request path.', ['LB → nginx → gateway → app', 'when to add layers', 'health checks'], 'EdgeStackSim walkthrough — Next hop through DNS to database.', ['First hop after DNS?', 'When add a gateway?']),
}

export const sqlChapterGuides: Record<string, TeacherGuide> = {
  'sql-intro': chapterGuide('Why SQL', 'Explain declarative SQL over relational tables.', ['Tables and rows', 'Declarative queries', 'Portable across engines'], 'Relate to the sample customers/orders schema used later.', ['What is declarative SQL?', 'Where does data live in a relational DB?']),
  'sql-tables': chapterGuide('Tables & queries', 'Write SELECT, WHERE, ORDER BY, LIMIT.', ['SELECT/FROM/WHERE', 'ORDER BY and LIMIT', 'JOIN and GROUP BY intro'], 'Sketch a query on the board before opening the playground.', ['Which clause filters rows?', 'What does JOIN combine?']),
  'sql-schema': chapterGuide('Schema & keys', 'Define primary and foreign keys and relationships.', ['Primary key', 'Foreign key', 'Normalization trade-offs'], 'Draw customers ↔ orders ERD.', ['What does a foreign key enforce?', 'When denormalize?']),
  'sql-writes': chapterGuide('SQL writes', 'Use INSERT, UPDATE, DELETE with WHERE and transactions.', ['INSERT/UPDATE/DELETE', 'WHERE on writes', 'Transactions'], 'Show an unqualified DELETE caution tale.', ['Why use WHERE on UPDATE?', 'Why transactions for transfers?']),
  'sql-indexes': chapterGuide('SQL indexes', 'Explain scan vs seek and selectivity.', ['B-tree index', 'Sequential scan', 'Write cost'], 'Toggle index in IndexScanSim; compare row counts.', ['When does an index help?', 'What does EXPLAIN show?']),
  'sql-transactions': chapterGuide('Transactions', 'BEGIN/COMMIT/ROLLBACK and lost updates.', ['Atomicity', 'Isolation', 'Lost update'], 'Run TransactionSim with and without transactions.', ['What does ROLLBACK do?', 'When do lost updates happen?']),
  'sql-advanced': chapterGuide('Advanced SQL', 'Compare JOIN types, HAVING, and subqueries.', ['INNER vs LEFT JOIN', 'HAVING vs WHERE', 'Subqueries'], 'Run LEFT JOIN sample in playground after theory.', ['What does LEFT JOIN keep?', 'HAVING filters what?']),
  'sql-conn-sqlite': chapterGuide('SQLite', 'Connect with sqlite3 and ? placeholders.', ['sqlite3 module', ':memory: vs file', 'Parameterized queries'], 'Run Connect & query snippet.', ['Why ? placeholders?', 'When use SQLite?']),
  'sql-conn-postgres': chapterGuide('Postgres drivers', 'Use psycopg2/asyncpg and DSN strings.', ['DSN format', '%s placeholders', 'Server vs embedded'], 'Run Postgres-style connector snippet.', ['What is a DSN?', 'psycopg2 connects to what?']),
  'sql-conn-pool': chapterGuide('Connection pools', 'Reuse connections with acquire/release.', ['Pool exhaustion', 'Warm connections', 'Release after use'], 'Exhaust the pool in the snippet.', ['Why pools in web apps?', 'What happens when pool is empty?']),
  'sql-conn-orm': chapterGuide('SQLAlchemy ORM', 'Map classes to tables; know ORM trade-offs.', ['ORM generates SQL', 'Session API', 'Raw SQL for hot paths'], 'Run ORM-style query snippet; discuss when to drop to SQL.', ['What does an ORM do?', 'When prefer raw SQL?']),
  'sql-playground': chapterGuide('SQL playground', 'Run live SQLite queries on sample data.', ['Real SQLite in browser', 'Joins and aggregates', 'Writes change data'], 'Students run LEFT JOIN and INSERT samples.', ['How to find customers with zero orders?', 'What does HAVING filter?']),
  'sql-labs': chapterGuide('Python SQL labs', 'Practice sqlite3 patterns in Python.', ['Parameterization', 'JOIN in Python', 'Injection safety'], 'Run Parameterized query with malicious-looking input.', ['How do parameters stop injection?', 'Name the JOIN snippet output.']),
  'sql-hood': chapterGuide('SQL internals', 'Explain indexes, planners, and injection.', ['B-tree indexes', 'EXPLAIN plans', 'Never concatenate user input'], 'Contrast string-built query vs parameterized.', ['Why indexes help?', 'What does EXPLAIN show?']),
}

export const mongodbChapterGuides: Record<string, TeacherGuide> = {
  'mongodb-intro': chapterGuide('Why MongoDB', 'Contrast documents with relational tables.', ['Document model', 'Flexible schema', 'Embed vs reference'], 'Compare one order document vs normalized SQL tables.', ['What is a document?', 'When pick MongoDB over SQL?']),
  'mongodb-documents': chapterGuide('Documents', 'Describe collections, _id, and flexible fields.', ['_id primary key', 'Embedded arrays', 'References'], 'Run Documents as dicts snippet.', ['What is a collection?', 'Can documents differ in shape?']),
  'mongodb-queries': chapterGuide('Queries', 'Write find filters with operators.', ['Equality filters', '$gt and $in', 'JSON query syntax'], 'Filter London orders then amount > 100.', ['What does $gt mean?', 'How is find different from SQL WHERE?']),
  'mongodb-writes': chapterGuide('Writes', 'Use insertOne, updateMany, deleteMany with $set.', ['insertOne', 'updateMany + $set', 'Schema discipline'], 'Discuss typo fields without validation.', ['What does $set do?', 'Why schema discipline still matters?']),
  'mongodb-aggregation': chapterGuide('Aggregation', 'Build pipelines with $match, $group, $sort.', ['Pipeline stages', '$group + $sum', 'Like SQL GROUP BY'], 'Run Group & sum snippet; mirror in playground.', ['What is $group for?', 'First stage you usually use?']),
  'mongodb-conn-pymongo': chapterGuide('PyMongo', 'Use MongoClient and collection methods.', ['MongoClient', 'find/insert_one', 'Sync driver'], 'Insert and find_one in PyMongo snippet.', ['What does insert_one return?', 'How pick database?']),
  'mongodb-conn-uri': chapterGuide('MongoDB URI', 'Parse mongodb+srv connection strings.', ['Credentials in URI', 'retryWrites', 'Never commit secrets'], 'Parse sample Atlas URI in snippet.', ['What does mongodb+srv imply?', 'Where put credentials?']),
  'mongodb-conn-motor': chapterGuide('Motor', 'Await async database calls.', ['Motor wraps PyMongo', 'asyncio integration', 'FastAPI pairing'], 'Run Motor async snippet; tie to FastAPI lesson.', ['Why Motor in FastAPI?', 'What happens during await?']),
  'mongodb-conn-odm': chapterGuide('ODMs', 'Use Beanie/MongoEngine for typed documents.', ['ODM vs raw driver', 'Pydantic validation', 'When ODM helps'], 'Walk through Beanie Order model example.', ['When use ODM?', 'ODM vs PyMongo ad-hoc queries?']),
  'mongodb-playground': chapterGuide('Mongo playground', 'Run shell commands on in-memory docs.', ['find and aggregate', 'insert/update', 'Compare to SQL JOIN'], 'Aggregate revenue then insert a document.', ['How add $limit stage?', 'Embed vs JOIN mentally?']),
  'mongodb-labs': chapterGuide('Python labs', 'Filter and aggregate without a server.', ['Dict documents', 'Operator simulation', 'PyMongo patterns'], 'Extend Filter documents for $in.', ['How filter amount > 100?', 'What does aggregation compute?']),
  'mongodb-hood': chapterGuide('MongoDB scale', 'Choose embed vs reference; indexes and sharding.', ['Embed vs reference', 'Indexes on filter fields', 'Sharding for scale'], 'Whiteboard embed order lines vs customer reference.', ['When embed vs reference?', 'What does sharding do?']),
}

export const containerizationChapterGuides: Record<string, TeacherGuide> = {
  'container-intro': chapterGuide('Why containers', 'Contrast VMs and containers; link to compute scaling.', ['Shared kernel', 'Image portability', 'OCI standards'], 'VmContainerCompare toggle; discuss boot time.', ['Containers vs VMs — kernel?', 'What is an image?']),
  'docker-images': chapterGuide('Images & layers', 'Explain layer cache, tags, registries.', ['Dockerfile layers', 'docker build/push', '.dockerignore'], 'ImageLayersSim step build.', ['docker build creates?', 'Why layer cache?']),
  'docker-containers': chapterGuide('Container lifecycle', 'Run, ps, logs, exec, stop, rm.', ['docker run flags', 'Port mapping', 'Detached mode'], 'DockerCliSim or Wasmer shell lab.', ['docker run creates?', '-p maps which ports?']),
  'docker-dockerfile': chapterGuide('Dockerfile', 'FROM/COPY/RUN/CMD and multi-stage.', ['Multi-stage builds', 'ENTRYPOINT vs CMD', 'Small runtime images'], 'DockerfileEditorSim validate.', ['Multi-stage builds mainly?', 'Missing CMD issue?']),
  'docker-networks': chapterGuide('Docker networking', 'Bridge vs host; publish ports; DNS on custom networks.', ['bridge default', 'user-defined networks', '-p host:container'], 'DockerNetworkSim port diagram.', ['DNS between containers when?']),
  'docker-volumes': chapterGuide('Volumes', 'Named volumes vs bind mounts; data survival.', ['Ephemeral container FS', 'Named volume', 'Bind mount dev'], 'DockerVolumeSim rm test.', ['Volumes help because?']),
  'compose-intro': chapterGuide('Compose model', 'YAML services and depends_on graph.', ['services key', 'depends_on', 'networks/volumes top-level'], 'ComposeGraphSim edit YAML.', ['depends_on ensures?']),
  'compose-services': chapterGuide('Compose up', 'Multi-service stack web+api+db.', ['compose up -d', 'environment', 'compose logs/exec'], 'ComposeSim startup order.', ['compose down removes?']),
  'compose-production': chapterGuide('Compose prod', 'Profiles, overrides, healthchecks, scale.', ['compose.override.yml', 'profiles', 'healthcheck condition'], 'ComposeSim with profiles.', ['service_healthy waits for?']),
  'k8s-intro': chapterGuide('Why k8s', 'Desired state reconciliation at scale.', ['Self-healing', 'Rolling updates', 'Scheduling'], 'K8sWorkloadSim scale replicas.', ['K8s is for?']),
  'k8s-architecture': chapterGuide('K8s architecture', 'Control plane vs node components.', ['API server', 'etcd', 'kubelet/kube-proxy'], 'K8sClusterSim click tour.', ['State stored in?']),
  'k8s-workloads': chapterGuide('Workloads', 'Pods, Deployments, StatefulSet, DaemonSet.', ['Pod smallest unit', 'Deployment replicas', 'Controller loops'], 'K8sWorkloadSim desired vs actual.', ['Deployments manage?']),
  'k8s-services': chapterGuide('Services', 'ClusterIP, NodePort, LoadBalancer.', ['Stable VIP', 'Selectors', 'kube-proxy'], 'K8sServiceSim route requests.', ['ClusterIP reachable where?']),
  'k8s-ingress': chapterGuide('Ingress', 'HTTP host/path routing and TLS.', ['Ingress vs LB', 'ingress controller', 'cert-manager mention'], 'IngressSim host/path match.', ['Ingress routes?']),
  'k8s-networking': chapterGuide('K8s networking', 'CNI, pod IPs, CoreDNS.', ['Pod CIDR', 'Service DNS', 'NetworkPolicy intro'], 'K8sNetworkingSim lookup.', ['Service DNS suffix?']),
  'k8s-storage': chapterGuide('Storage', 'PV, PVC, StorageClass, CSI.', ['Dynamic provisioning', 'Bound phase', 'Mount in pod'], 'K8sStorageSim apply PVC.', ['PVC Bound means?']),
  'k8s-config-secrets': chapterGuide('Config & secrets', 'ConfigMap vs Secret; mount modes.', ['env vs volume', 'base64 not encryption', 'sealed-secrets'], 'ConfigSecretsSim toggle mount.', ['Secrets in etcd are?']),
  'k8s-commands': chapterGuide('kubectl', 'get, describe, apply, logs, exec, scale, rollout.', ['Declarative apply', 'Imperative debug', 'Contexts/namespaces'], 'KubectlLab command drill.', ['kubectl apply is?']),
  'k8s-nodes': chapterGuide('Node ops', 'Cordon, drain, taints/tolerations.', ['SchedulingDisabled', 'Eviction', 'GPU taints'], 'K8sNodeSim cordon/drain.', ['drain before?']),
  'k8s-operators-builtin': chapterGuide('Built-in controllers', 'Deployment reconciliation loop.', ['Observe-compare-act', 'ReplicaSet owner', 'Self-healing'], 'K8sOperatorSim builtin mode.', ['Deployment controller creates?']),
  'k8s-operators-custom': chapterGuide('Custom operators', 'CRD + controller pattern.', ['CRD', 'Operator SDK', 'cert-manager example'], 'K8sOperatorSim custom mode.', ['Operators package?']),
  'platforms-managed-k8s': chapterGuide('EKS/GKE/AKS', 'Managed control planes and IAM.', ['Managed CP', 'Node pools', 'Workload identity'], 'PlatformCompare eks/gke/aks.', ['EKS stands for?']),
  'platforms-ecs-rancher': chapterGuide('ECS & Rancher', 'ECS tasks vs k8s; Rancher multi-cluster.', ['ECS task definition', 'Fargate', 'Docker Desktop dev'], 'PlatformCompare ecs/rancher/desktop.', ['ECS uses?']),
  'container-capstone': chapterGuide('Capstone', 'Image → compose → k8s rollout vertical slice.', ['CI builds image', 'Compose integration test', 'GitOps optional'], 'ContainerCapstoneSim steps; tie to CI/CD chapter.', ['First capstone step?']),
}
