import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const webLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'web-reverse-proxy',
    title: 'Reverse proxies',
    tagline: 'One public door in front of many private servers.',
    summary: 'Learn forward vs reverse proxies, why nginx sits in front of apps, and how TLS and static files terminate at the edge.',
    group: 'web',
    minutes: 6,
    level: 'Intermediate',
    modelTitle: 'Reverse proxy basics',
    hasPlayground: true,
    playgroundTitle: 'Route through nginx',
  }),
  chapterMeta({
    id: 'web-nginx-routing',
    title: 'nginx API routing',
    tagline: 'Route /api, /static, and hostnames to different upstreams.',
    summary: 'Use nginx location blocks, proxy_pass, and upstream pools to route API traffic to the right backend services.',
    group: 'web',
    minutes: 6,
    level: 'Intermediate',
    modelTitle: 'Path & upstream routing',
    hasPlayground: true,
    playgroundTitle: 'Route requests live',
  }),
  chapterMeta({
    id: 'web-api-gateway',
    title: 'API gateways',
    tagline: 'Auth, keys, quotas, and routing in one place.',
    summary: 'Compare reverse proxies with API gateways — centralized auth, API keys, request transformation, and multi-service routing.',
    group: 'web',
    minutes: 6,
    level: 'Intermediate',
    modelTitle: 'Gateway responsibilities',
    hasPlayground: true,
    playgroundTitle: 'Gateway simulator',
  }),
  chapterMeta({
    id: 'web-rate-limiting',
    title: 'Rate limiting & throttling',
    tagline: 'Protect APIs with token buckets and 429 responses.',
    summary: 'Apply per-IP and per-key limits, understand burst vs sustained rates, and return HTTP 429 when clients exceed quotas.',
    group: 'web',
    minutes: 6,
    level: 'Intermediate',
    modelTitle: 'Throttling patterns',
    hasPlayground: true,
    playgroundTitle: 'Throttle requests live',
    hasHood: true,
  }),
  chapterMeta({
    id: 'web-edge-stack',
    title: 'Edge stack in production',
    tagline: 'How nginx, gateways, and limits fit together.',
    summary: 'See a typical production path: DNS → load balancer → reverse proxy/gateway → rate limit → app servers.',
    group: 'web',
    minutes: 6,
    level: 'Advanced',
    modelTitle: 'Production edge flow',
    hasPlayground: true,
    playgroundTitle: 'Walk the edge stack',
    hasHood: true,
  }),
]
