import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const mongodbLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'mongodb-intro',
    title: 'Why MongoDB',
    tagline: 'Flexible documents instead of rigid tables.',
    summary: 'See when document databases fit — nested data, evolving schemas, and embed vs reference.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'Document databases',
    hasPlayground: true,
    playgroundTitle: 'Find documents lab',
  }),
  chapterMeta({
    id: 'mongodb-documents',
    title: 'Documents & collections',
    tagline: '_id, flexible schema, arrays, references.',
    summary: 'Store JSON-like documents in collections with optional embedded arrays and references.',
    group: 'mongodb',
    minutes: 5,
    modelTitle: 'Documents & collections',
    hasPlayground: true,
    playgroundTitle: 'Document explorer',
  }),
  chapterMeta({
    id: 'mongodb-queries',
    title: 'Finding documents',
    tagline: 'JSON filters and query operators.',
    summary: 'Query with equality filters and operators like $gt, $in, and $regex.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'Query filters',
    hasPlayground: true,
    playgroundTitle: 'Query filters lab',
  }),
  chapterMeta({
    id: 'mongodb-writes',
    title: 'Insert, update & delete',
    tagline: 'insertOne, updateMany, deleteMany.',
    summary: 'Write documents with insertOne and patch fields using $set in updateMany.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'Document writes',
    hasPlayground: true,
    playgroundTitle: 'Write commands lab',
  }),
  chapterMeta({
    id: 'mongodb-aggregation',
    title: 'Aggregation pipelines',
    tagline: '$match, $group, $sort, $limit.',
    summary: 'Build pipelines to filter, group, and summarize documents like SQL GROUP BY.',
    group: 'mongodb',
    minutes: 5,
    modelTitle: 'Aggregation',
    hasPlayground: true,
    playgroundTitle: 'Aggregation lab',
  }),
  chapterMeta({
    id: 'mongodb-conn-pymongo',
    title: 'PyMongo driver',
    tagline: 'Synchronous Python client.',
    summary: 'Use MongoClient, pick a database/collection, and call find/insert_one.',
    group: 'mongodb',
    minutes: 5,
    modelTitle: 'PyMongo',
    hasPlayground: true,
    playgroundTitle: 'PyMongo lab',
  }),
  chapterMeta({
    id: 'mongodb-conn-uri',
    title: 'Connection URIs',
    tagline: 'mongodb+srv, auth, and options.',
    summary: 'Parse URIs for Atlas or self-hosted MongoDB with TLS and write concern options.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'Connection strings',
    hasPlayground: true,
    playgroundTitle: 'URI parser lab',
  }),
  chapterMeta({
    id: 'mongodb-conn-motor',
    title: 'Motor (async driver)',
    tagline: 'await database calls in asyncio.',
    summary: 'Use Motor with FastAPI handlers so the event loop stays responsive during I/O.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'Motor async',
    hasPlayground: true,
    playgroundTitle: 'Async lab',
  }),
  chapterMeta({
    id: 'mongodb-conn-odm',
    title: 'ODMs (Beanie / MongoEngine)',
    tagline: 'Typed models for documents.',
    summary: 'Map Pydantic-style classes to collections with Beanie or MongoEngine.',
    group: 'mongodb',
    minutes: 4,
    modelTitle: 'ODMs',
    hasPlayground: true,
    playgroundTitle: 'ODM model lab',
  }),
  chapterMeta({
    id: 'mongodb-playground',
    title: 'MongoDB playground',
    tagline: 'Live document shell in the browser.',
    summary: 'Run find, aggregate, and write commands against an in-memory document store.',
    group: 'mongodb',
    minutes: 8,
    modelTitle: 'Shell commands',
    hasPlayground: true,
    playgroundTitle: 'Run commands live',
  }),
  chapterMeta({
    id: 'mongodb-labs',
    title: 'Python document labs',
    tagline: 'Filter, aggregate, and connect in Python.',
    summary: 'Practice documents-as-dicts, operators, grouping, and PyMongo patterns.',
    group: 'mongodb',
    minutes: 6,
    modelTitle: 'Python + MongoDB',
    hasPlayground: true,
    playgroundTitle: 'Code lab',
  }),
  chapterMeta({
    id: 'mongodb-hood',
    title: 'Embed, indexes & sharding',
    tagline: 'Production-scale document design.',
    summary: 'Choose embed vs reference, index query fields, and understand replication/sharding.',
    group: 'mongodb',
    minutes: 5,
    modelTitle: 'Overview',
    hasPlayground: true,
    playgroundTitle: 'Aggregate lab',
    hasHood: true,
  }),
]
