import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const kafkaLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'kafka-event-streaming',
    title: 'Event streaming platform',
    tagline: 'A distributed commit log for real-time data — not just a queue.',
    summary:
      'Contrast Kafka with traditional message queues, learn the event-streaming mindset, and map common use cases from metrics to CDC.',
    group: 'kafka',
    minutes: 8,
    level: 'Intermediate',
    modelTitle: 'Logs, events & use cases',
    extraSections: [
      { id: 'compare', title: 'Kafka vs message queues' },
      { id: 'cases', title: 'Where teams use Kafka' },
    ],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-topics-log',
    title: 'Topics & the commit log',
    tagline: 'Topics are append-only logs; offsets are your bookmark.',
    summary:
      'Understand topics, records, segments, offsets, and retention policies that make Kafka a replayable system of record.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Topic anatomy',
    extraSections: [{ id: 'retention', title: 'Retention & cleanup' }],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-partitions',
    title: 'Partitions & record keys',
    tagline: 'Scale throughput by sharding ordered sub-logs.',
    summary:
      'Learn how partitions enable parallelism, how keys pick a partition, and when you sacrifice global ordering.',
    group: 'kafka',
    minutes: 8,
    modelTitle: 'Sharding & ordering',
    hasPlayground: true,
    playgroundTitle: 'In-browser Kafka lab',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-producers',
    title: 'Producers',
    tagline: 'Choose durability, batching, and partitioning on the write path.',
    summary:
      'Covers producer configuration: acks, idempotence, compression, headers, and how records land on partitions.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Writing events',
    extraSections: [{ id: 'config', title: 'Important producer settings' }],
    hasPlayground: true,
    playgroundTitle: 'Try partitioning code',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-consumers',
    title: 'Consumers & offsets',
    tagline: 'Consumers track progress with offsets — and can replay.',
    summary:
      'Poll loops, offset commits, isolation levels, and why replay makes Kafka different from classic MQ delete-on-read.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Reading the log',
    extraSections: [{ id: 'commits', title: 'Commit strategies' }],
    hasPlayground: true,
    playgroundTitle: 'Producer & consumer code lab',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-consumer-groups',
    title: 'Consumer groups',
    tagline: 'Scale consumption horizontally without duplicate work in a group.',
    summary:
      'Group coordination, partition assignment, rebalances, the internal offsets topic, and consumer lag.',
    group: 'kafka',
    minutes: 8,
    modelTitle: 'Group mechanics',
    hasPlayground: true,
    playgroundTitle: 'Consumer group lab',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-brokers-replication',
    title: 'Brokers & replication',
    tagline: 'Partitions are replicated for fault tolerance across brokers.',
    summary:
      'Leaders, followers, in-sync replicas (ISR), controller role, and the move from ZooKeeper to KRaft metadata.',
    group: 'kafka',
    minutes: 8,
    modelTitle: 'Cluster layout',
    extraSections: [{ id: 'kraft', title: 'KRaft metadata quorum' }],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-reliability',
    title: 'Durability & availability',
    tagline: 'Tune min ISR and acks to match your SLA.',
    summary:
      'Trade latency for durability using replication, min.insync.replicas, and unclean leader election risks.',
    group: 'kafka',
    minutes: 6,
    modelTitle: 'Replication guarantees',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-delivery-semantics',
    title: 'Delivery semantics',
    tagline: 'At-least-once is easy; exactly-once needs discipline.',
    summary:
      'Compare at-most / at-least / exactly-once paths, idempotent consumers, transactions, and Streams processing guarantees.',
    group: 'kafka',
    minutes: 8,
    modelTitle: 'End-to-end guarantees',
    extraSections: [{ id: 'eos', title: 'Exactly-once in practice' }],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-compaction',
    title: 'Log compaction',
    tagline: 'Keep the latest value per key — a changelog, not a mailbox.',
    summary:
      'Compacted topics, tombstones, changelog streams, and how compaction supports stateful stream processing.',
    group: 'kafka',
    minutes: 6,
    modelTitle: 'Compaction model',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-serialization',
    title: 'Serialization & schemas',
    tagline: 'Agree on data shape with Avro, Protobuf, and Schema Registry.',
    summary:
      'Wire formats, schema evolution rules, and why registries matter in polyglot pipelines.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Contracts on the wire',
    extraSections: [{ id: 'evolution', title: 'Schema evolution' }],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-connect',
    title: 'Kafka Connect',
    tagline: 'Move data in and out with connectors instead of bespoke jobs.',
    summary:
      'Source and sink connectors, single message transforms, JDBC and CDC patterns, and dead-letter handling.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Connect architecture',
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-streams',
    title: 'Kafka Streams & ksqlDB',
    tagline: 'Process streams with KStream/KTable and optional SQL.',
    summary:
      'Stateful stream processing, joins and windowing, state stores, stream-table duality, and exactly_once_v2.',
    group: 'kafka',
    minutes: 9,
    modelTitle: 'Stream processing',
    extraSections: [{ id: 'duality', title: 'Stream–table duality' }],
    hasHood: true,
  }),
  chapterMeta({
    id: 'kafka-operations',
    title: 'Operations & security',
    tagline: 'Design topics, watch lag, and lock down access.',
    summary:
      'Operational metrics, quotas, ACLs, SASL/TLS overview, and a practical topic-design checklist.',
    group: 'kafka',
    minutes: 7,
    modelTitle: 'Running Kafka in production',
    extraSections: [{ id: 'checklist', title: 'Topic design checklist' }],
    hasHood: true,
  }),
]
