import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const databasesLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'databases-intro',
    title: 'Why databases',
    tagline: 'Durable storage beyond process memory.',
    summary: 'Learn why applications persist data to disk or a server instead of keeping everything in RAM.',
    group: 'databases',
    minutes: 4,
    modelTitle: 'Durable state',
  }),
  chapterMeta({
    id: 'databases-architecture',
    title: 'Clients, servers & drivers',
    tagline: 'How your app talks to a database engine.',
    summary: 'Contrast embedded databases with client-server engines and see how drivers translate API calls.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'Architecture',
  }),
  chapterMeta({
    id: 'databases-models',
    title: 'Data models',
    tagline: 'Relational, document, key-value, and graph.',
    summary: 'Compare the major database families and the shapes of data each one optimizes for.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'Database families',
  }),
  chapterMeta({
    id: 'databases-acid',
    title: 'ACID & transactions',
    tagline: 'Atomicity, consistency, isolation, durability.',
    summary: 'Understand transactions that group writes and why ACID matters for money, inventory, and accounts.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'ACID properties',
  }),
  chapterMeta({
    id: 'databases-schemas',
    title: 'Schema design',
    tagline: 'Normalization, constraints, and evolution.',
    summary: 'Balance rigid schemas with flexibility — keys, constraints, migrations, and when to denormalize.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'Schema thinking',
  }),
  chapterMeta({
    id: 'databases-choosing',
    title: 'SQL vs MongoDB',
    tagline: 'Pick the right store for the job.',
    summary: 'Use a decision framework: joins vs embed, schema stability, query patterns, and team skills.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'Choosing a database',
  }),
  chapterMeta({
    id: 'databases-hood',
    title: 'Replication & backups',
    tagline: 'Production persistence under the hood.',
    summary: 'Learn replication, backups, connection pooling, and migrations at a high level before diving into SQL or MongoDB.',
    group: 'databases',
    minutes: 5,
    modelTitle: 'Overview',
    hasHood: true,
  }),
]
