import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const sqlLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'sql-intro',
    title: 'Why SQL',
    tagline: 'Declarative queries over relational tables.',
    summary: 'Learn why SQL is durable, declarative, and works across Postgres, MySQL, and SQLite.',
    group: 'sql',
    minutes: 4,
    modelTitle: 'Tables and queries',
    hasPlayground: true,
    playgroundTitle: 'Run your first query',
  }),
  chapterMeta({
    id: 'sql-tables',
    title: 'Tables & queries',
    tagline: 'SELECT, WHERE, ORDER BY, JOIN, GROUP BY.',
    summary: 'Read data with SELECT, filter with WHERE, sort, join tables, and aggregate rows.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'Core SQL clauses',
    hasPlayground: true,
    playgroundTitle: 'Filter & join lab',
  }),
  chapterMeta({
    id: 'sql-schema',
    title: 'Schema, keys & relationships',
    tagline: 'Primary keys, foreign keys, normalization.',
    summary: 'Model one-to-many and many-to-many relationships with keys and normalization.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'Keys & relationships',
    hasPlayground: true,
    playgroundTitle: 'Join keys lab',
  }),
  chapterMeta({
    id: 'sql-writes',
    title: 'Insert, update & delete',
    tagline: 'INSERT, UPDATE, DELETE, and transactions.',
    summary: 'Modify data safely with WHERE clauses and wrap related writes in transactions.',
    group: 'sql',
    minutes: 4,
    modelTitle: 'Writing data',
    hasPlayground: true,
    playgroundTitle: 'Write operations lab',
  }),
  chapterMeta({
    id: 'sql-advanced',
    title: 'Joins, aggregates & subqueries',
    tagline: 'LEFT JOIN, HAVING, nested SELECT.',
    summary: 'Compare INNER vs LEFT JOIN, filter groups with HAVING, and nest subqueries.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'Advanced queries',
    hasPlayground: true,
    playgroundTitle: 'Advanced queries lab',
  }),
  chapterMeta({
    id: 'sql-conn-sqlite',
    title: 'SQLite & sqlite3',
    tagline: 'Embedded database with Python stdlib.',
    summary: 'Connect with sqlite3, use ? placeholders, and run queries in memory or on disk.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'sqlite3 connector',
    hasPlayground: true,
    playgroundTitle: 'Connect & query lab',
  }),
  chapterMeta({
    id: 'sql-conn-postgres',
    title: 'PostgreSQL drivers',
    tagline: 'psycopg2, asyncpg, and DSN strings.',
    summary: 'Connect to production Postgres with psycopg2 or asyncpg and %s placeholders.',
    group: 'sql',
    minutes: 4,
    modelTitle: 'Postgres connectors',
    hasPlayground: true,
    playgroundTitle: 'Connector simulation',
  }),
  chapterMeta({
    id: 'sql-conn-pool',
    title: 'Connection pools',
    tagline: 'Reuse warm connections in web apps.',
    summary: 'Understand why pools matter and how acquire/release prevents connection leaks.',
    group: 'sql',
    minutes: 4,
    modelTitle: 'Pooling pattern',
    hasPlayground: true,
    playgroundTitle: 'Pool lab',
  }),
  chapterMeta({
    id: 'sql-conn-orm',
    title: 'ORMs & SQLAlchemy',
    tagline: 'Map Python classes to tables.',
    summary: 'Use SQLAlchemy ORM for CRUD and migrations; drop to raw SQL for hot paths.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'ORM basics',
    hasPlayground: true,
    playgroundTitle: 'ORM query lab',
    hasHood: true,
  }),
  chapterMeta({
    id: 'sql-playground',
    title: 'SQL playground',
    tagline: 'Live SQLite in your browser.',
    summary: 'Run real SQL against a sample shop database with joins, aggregates, and writes.',
    group: 'sql',
    minutes: 8,
    modelTitle: 'Sample database',
    hasPlayground: true,
    playgroundTitle: 'Run SQL live',
  }),
  chapterMeta({
    id: 'sql-labs',
    title: 'Python SQL labs',
    tagline: 'sqlite3 snippets and parameterized queries.',
    summary: 'Practice connect, parameterize, JOIN, pool, and ORM patterns in Python.',
    group: 'sql',
    minutes: 6,
    modelTitle: 'Python + SQL',
    hasPlayground: true,
    playgroundTitle: 'Code lab',
  }),
  chapterMeta({
    id: 'sql-hood',
    title: 'Indexes, planners & injection',
    tagline: 'Performance and security under the hood.',
    summary: 'Learn indexes, EXPLAIN/query plans, and why parameterized queries stop SQL injection.',
    group: 'sql',
    minutes: 5,
    modelTitle: 'Overview',
    hasPlayground: true,
    playgroundTitle: 'Join lab',
    hasHood: true,
  }),
]
