import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

const G = 'containerization' as const

export const containerizationLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'container-intro',
    title: 'Why containers?',
    tagline: 'Package apps with their dependencies — lighter than VMs, portable everywhere.',
    summary: 'Compare VMs and containers, see the shared-kernel model, and connect to compute scaling.',
    group: G,
    minutes: 10,
    modelTitle: 'VMs vs containers',
    hasPlayground: true,
    playgroundTitle: 'Compare stacks',
    hasHood: true,
    extraSections: [{ id: 'when-containers', title: 'When containers win' }],
  }),
  chapterMeta({
    id: 'docker-images',
    title: 'Images & layers',
    tagline: 'Immutable templates built from cached Dockerfile layers.',
    summary: 'Understand image tags, registries, layer caching, and docker build/push/pull.',
    group: G,
    minutes: 12,
    modelTitle: 'Images & registries',
    hasPlayground: true,
    playgroundTitle: 'Build layers',
    extraSections: [{ id: 'tags-digests', title: 'Tags vs digests' }],
  }),
  chapterMeta({
    id: 'docker-containers',
    title: 'Containers & lifecycle',
    tagline: 'Running instances — start, stop, logs, and port maps.',
    summary: 'Run containers from images with docker run, inspect with ps/logs, and manage lifecycle.',
    group: G,
    minutes: 12,
    modelTitle: 'Container lifecycle',
    hasPlayground: true,
    playgroundTitle: 'Docker CLI lab',
    extraSections: [{ id: 'lifecycle-states', title: 'Lifecycle states' }],
  }),
  chapterMeta({
    id: 'docker-dockerfile',
    title: 'Dockerfile deep dive',
    tagline: 'FROM, COPY, RUN, multi-stage builds, and .dockerignore.',
    summary: 'Write production Dockerfiles with multi-stage builds and validate instructions.',
    group: G,
    minutes: 12,
    modelTitle: 'Dockerfile instructions',
    hasPlayground: true,
    playgroundTitle: 'Edit & build',
    extraSections: [{ id: 'dockerignore', title: '.dockerignore & security' }],
  }),
  chapterMeta({
    id: 'docker-networks',
    title: 'Networks & ports',
    tagline: 'Bridge networks, port mapping, and container DNS.',
    summary: 'Map host ports, choose network modes, and reach services by name on user-defined networks.',
    group: G,
    minutes: 10,
    modelTitle: 'Networking modes',
    hasPlayground: true,
    playgroundTitle: 'Map ports live',
    extraSections: [{ id: 'dns-publish', title: 'DNS & publishing' }],
  }),
  chapterMeta({
    id: 'docker-volumes',
    title: 'Volumes & bind mounts',
    tagline: 'Persist data outside the ephemeral container filesystem.',
    summary: 'Named volumes vs bind mounts — what survives docker rm.',
    group: G,
    minutes: 10,
    modelTitle: 'Persistent storage',
    hasPlayground: true,
    playgroundTitle: 'Volume survival',
    extraSections: [{ id: 'choose-mount', title: 'Choosing a mount type' }],
  }),
  chapterMeta({
    id: 'compose-intro',
    title: 'Compose mental model',
    tagline: 'One YAML file defines a multi-service stack.',
    summary: 'Parse compose files into a service dependency graph.',
    group: G,
    minutes: 10,
    modelTitle: 'Services & dependencies',
    hasPlayground: true,
    playgroundTitle: 'Visualize the graph',
    extraSections: [{ id: 'compose-files', title: 'File layout' }],
  }),
  chapterMeta({
    id: 'compose-services',
    title: 'Services & depends_on',
    tagline: 'Wire web, API, and database with environment variables.',
    summary: 'Bring up multi-container stacks with docker compose up and ordered startup.',
    group: G,
    minutes: 12,
    modelTitle: 'Multi-service stacks',
    hasPlayground: true,
    playgroundTitle: 'Compose up',
    extraSections: [{ id: 'env-wiring', title: 'Wiring with environment' }],
  }),
  chapterMeta({
    id: 'compose-production',
    title: 'Compose in production',
    tagline: 'Profiles, overrides, healthchecks, and scaling.',
    summary: 'Use compose.override.yml, profiles, and docker compose scale for real workflows.',
    group: G,
    minutes: 12,
    modelTitle: 'Prod patterns',
    hasPlayground: true,
    playgroundTitle: 'Profiles & healthchecks',
    extraSections: [{ id: 'healthchecks', title: 'Healthchecks in practice' }],
  }),
  chapterMeta({
    id: 'k8s-intro',
    title: 'Why orchestration?',
    tagline: 'When one host is not enough — schedule, heal, and scale.',
    summary: 'Problems containers alone cannot solve: scheduling, self-healing, rolling updates.',
    group: G,
    minutes: 10,
    modelTitle: 'Orchestration problems',
    hasPlayground: true,
    playgroundTitle: 'Scale replicas',
    hasHood: true,
    extraSections: [{ id: 'pain-points', title: 'Problems Compose cannot solve alone' }],
  }),
  chapterMeta({
    id: 'k8s-architecture',
    title: 'Control plane & nodes',
    tagline: 'API server, etcd, scheduler, kubelet, and kube-proxy.',
    summary: 'Explore how the control plane and worker nodes cooperate.',
    group: G,
    minutes: 12,
    modelTitle: 'Cluster architecture',
    hasPlayground: true,
    playgroundTitle: 'Explore components',
    hasHood: true,
    extraSections: [{ id: 'deploy-path', title: 'Path of a deploy request' }],
  }),
  chapterMeta({
    id: 'k8s-workloads',
    title: 'Pods & controllers',
    tagline: 'Deployments, ReplicaSets, and desired state.',
    summary: 'Pods as the smallest unit; controllers reconcile replica counts.',
    group: G,
    minutes: 12,
    modelTitle: 'Workloads',
    hasPlayground: true,
    playgroundTitle: 'Scale a Deployment',
    extraSections: [{ id: 'labels', title: 'Labels & selectors' }],
  }),
  chapterMeta({
    id: 'k8s-services',
    title: 'Service types',
    tagline: 'ClusterIP, NodePort, and LoadBalancer.',
    summary: 'Stable endpoints for ephemeral pods — kube-proxy and cloud LBs.',
    group: G,
    minutes: 11,
    modelTitle: 'Kubernetes Services',
    hasPlayground: true,
    playgroundTitle: 'Route traffic',
    extraSections: [{ id: 'endpoints', title: 'Endpoints & readiness' }],
  }),
  chapterMeta({
    id: 'k8s-ingress',
    title: 'Ingress & TLS',
    tagline: 'HTTP routing by host and path at the edge.',
    summary: 'Ingress controllers terminate TLS and route to Services.',
    group: G,
    minutes: 10,
    modelTitle: 'Ingress rules',
    hasPlayground: true,
    playgroundTitle: 'Match requests',
    extraSections: [{ id: 'gateway-api', title: 'Gateway API (next step)' }],
  }),
  chapterMeta({
    id: 'k8s-networking',
    title: 'DNS, CNI & IPs',
    tagline: 'Pod IPs, Service cluster IPs, and CoreDNS.',
    summary: 'How pods get addresses and how services get stable DNS names.',
    group: G,
    minutes: 11,
    modelTitle: 'Cluster networking',
    hasPlayground: true,
    playgroundTitle: 'DNS lookup',
    extraSections: [{ id: 'dns-patterns', title: 'DNS patterns' }],
  }),
  chapterMeta({
    id: 'k8s-storage',
    title: 'PV, PVC & StorageClass',
    tagline: 'Persistent volumes and dynamic provisioning.',
    summary: 'Bind claims to volumes; StorageClass automates provisioning.',
    group: G,
    minutes: 11,
    modelTitle: 'Persistent storage',
    hasPlayground: true,
    playgroundTitle: 'Bind a PVC',
    extraSections: [{ id: 'stateful', title: 'StatefulSets & disks' }],
  }),
  chapterMeta({
    id: 'k8s-config-secrets',
    title: 'ConfigMaps & Secrets',
    tagline: 'Inject configuration without baking it into images.',
    summary: 'Mount config as env vars or files; understand Secret limitations.',
    group: G,
    minutes: 10,
    modelTitle: 'Config & secrets',
    hasPlayground: true,
    playgroundTitle: 'Mount config',
    extraSections: [{ id: 'gitops-secrets', title: 'Secrets in GitOps' }],
  }),
  chapterMeta({
    id: 'k8s-commands',
    title: 'kubectl for DevOps',
    tagline: 'get, describe, apply, logs, exec, scale, rollout.',
    summary: 'Day-to-day kubectl commands against a simulated API server.',
    group: G,
    minutes: 12,
    modelTitle: 'Essential kubectl',
    hasPlayground: true,
    playgroundTitle: 'kubectl lab',
    extraSections: [{ id: 'debug-flow', title: 'Debug workflow' }],
  }),
  chapterMeta({
    id: 'k8s-nodes',
    title: 'Node management',
    tagline: 'Cordon, drain, taints, and tolerations.',
    summary: 'Safely maintain nodes without dropping traffic unexpectedly.',
    group: G,
    minutes: 10,
    modelTitle: 'Node operations',
    hasPlayground: true,
    playgroundTitle: 'Cordon & drain',
    extraSections: [{ id: 'pdb', title: 'PodDisruptionBudgets' }],
  }),
  chapterMeta({
    id: 'k8s-operators-builtin',
    title: 'Built-in controllers',
    tagline: 'How the Deployment controller reconciles desired state.',
    summary: 'Watch the control loop that creates and deletes pods.',
    group: G,
    minutes: 10,
    modelTitle: 'Reconciliation loops',
    hasPlayground: true,
    playgroundTitle: 'Controller events',
    hasHood: true,
    extraSections: [{ id: 'level-triggered', title: 'Level-triggered vs edge-triggered' }],
  }),
  chapterMeta({
    id: 'k8s-operators-custom',
    title: 'CRDs & custom operators',
    tagline: 'Extend Kubernetes with your own APIs and controllers.',
    summary: 'Custom Resource Definitions and operators like cert-manager.',
    group: G,
    minutes: 11,
    modelTitle: 'Custom operators',
    hasPlayground: true,
    playgroundTitle: 'Operator reconcile',
    hasHood: true,
    extraSections: [{ id: 'crd-example', title: 'CRD mental model' }],
  }),
  chapterMeta({
    id: 'platforms-managed-k8s',
    title: 'EKS, GKE & AKS',
    tagline: 'Managed Kubernetes control planes in the cloud.',
    summary: 'Compare AWS, Google, and Azure managed offerings and IAM integration.',
    group: G,
    minutes: 10,
    modelTitle: 'Managed Kubernetes',
    hasPlayground: true,
    playgroundTitle: 'Compare platforms',
    extraSections: [{ id: 'node-strategy', title: 'Node strategy' }],
  }),
  chapterMeta({
    id: 'platforms-ecs-rancher',
    title: 'ECS, Rancher & Docker Desktop',
    tagline: 'Alternatives and multi-cluster tooling.',
    summary: 'ECS task model vs Kubernetes; Rancher for multi-cluster; local dev with Desktop.',
    group: G,
    minutes: 10,
    modelTitle: 'Platform choices',
    hasPlayground: true,
    playgroundTitle: 'Compare platforms',
    extraSections: [{ id: 'when-ecs', title: 'When ECS wins' }],
  }),
  chapterMeta({
    id: 'container-capstone',
    title: 'Ship a small stack',
    tagline: 'Dockerfile → Compose → Kubernetes → rollout.',
    summary: 'Walk through a vertical slice from image to cluster deployment.',
    group: G,
    minutes: 14,
    level: 'Advanced',
    modelTitle: 'End-to-end flow',
    hasPlayground: true,
    playgroundTitle: 'Capstone checklist',
    hasHood: true,
    extraSections: [{ id: 'rollback', title: 'Rollback plan' }],
  }),
]
