import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const reactLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'react-intro',
    title: 'Why React',
    tagline: 'UI = f(state) — building interfaces from components.',
    summary: 'Learn why React models UI as a function of state and how components compose into pages.',
    group: 'react',
    minutes: 4,
    modelTitle: 'UI as a function of state',
    hasPlayground: true,
    playgroundTitle: 'See UI = f(state)',
  }),
  chapterMeta({
    id: 'react-jsx-basics',
    title: 'Components & JSX',
    tagline: 'Functions that return HTML-like syntax.',
    summary: 'Write React components that return JSX and compose them like HTML tags.',
    group: 'react',
    minutes: 5,
    modelTitle: 'Components & JSX',
    hasPlayground: true,
    playgroundTitle: 'Compose components',
  }),
  chapterMeta({
    id: 'react-jsx-rules',
    title: 'JSX syntax rules',
    tagline: 'className, fragments, and curly-brace expressions.',
    summary: 'Master JSX differences from HTML: fragments, className, self-closing tags, and expressions.',
    group: 'react',
    minutes: 4,
    modelTitle: 'JSX syntax rules',
    hasPlayground: true,
    playgroundTitle: 'Fix JSX mistakes',
  }),
  chapterMeta({
    id: 'react-props',
    title: 'Props: data flows down',
    tagline: 'Read-only inputs from parent to child.',
    summary: 'Pass data into components via props — like function arguments for UI.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Props',
    hasPlayground: true,
    playgroundTitle: 'Props lab',
  }),
  chapterMeta({
    id: 'react-state',
    title: 'State with useState',
    tagline: 'Memory between renders.',
    summary: 'Use useState to remember values and trigger re-renders when they change.',
    group: 'react',
    minutes: 5,
    modelTitle: 'useState',
    hasPlayground: true,
    playgroundTitle: 'Counter lab',
  }),
  chapterMeta({
    id: 'react-events',
    title: 'Event handlers',
    tagline: 'onClick, onChange, and synthetic events.',
    summary: 'Wire user interactions to state setters with camelCase event props.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Event handlers',
    hasPlayground: true,
    playgroundTitle: 'Events lab',
  }),
  chapterMeta({
    id: 'react-lists',
    title: 'Lists & keys',
    tagline: 'map(), stable keys, and immutable updates.',
    summary: 'Render collections with .map(), assign stable keys, and update arrays immutably.',
    group: 'react',
    minutes: 5,
    modelTitle: 'Lists & keys',
    hasPlayground: true,
    playgroundTitle: 'Todo list lab',
  }),
  chapterMeta({
    id: 'react-effects',
    title: 'Side effects with useEffect',
    tagline: 'Fetch, subscribe, and sync after render.',
    summary: 'Run side effects after render with useEffect and control re-runs via the dependency array.',
    group: 'react',
    minutes: 5,
    modelTitle: 'useEffect',
    hasPlayground: true,
    playgroundTitle: 'Effects lab',
  }),
  chapterMeta({
    id: 'react-store-lift',
    title: 'Prop drilling & lifting state',
    tagline: 'When local state is not enough.',
    summary: 'Recognize prop drilling, lift shared state, and know when to graduate to Context or a store.',
    group: 'react',
    minutes: 6,
    modelTitle: 'Lifting state',
    hasPlayground: true,
    playgroundTitle: 'Lift & drill labs',
    hasHood: true,
  }),
  chapterMeta({
    id: 'react-store-context',
    title: 'Context API',
    tagline: 'Share values without threading props.',
    summary: 'Provide data at the top of a tree, custom hooks, performance pitfalls, and when Context fits.',
    group: 'react',
    minutes: 8,
    modelTitle: 'Context API',
    hasPlayground: true,
    playgroundTitle: 'Context labs',
    hasHood: true,
  }),
  chapterMeta({
    id: 'react-store-patterns',
    title: 'Context patterns',
    tagline: 'useReducer, split contexts, compound providers.',
    summary: 'Scale Context with reducers, separate state/dispatch providers, and know when to adopt a store.',
    group: 'react',
    minutes: 7,
    modelTitle: 'Context patterns',
    hasPlayground: true,
    playgroundTitle: 'Reducer + split context',
    hasHood: true,
  }),
  chapterMeta({
    id: 'react-store-external',
    title: 'External stores (Zustand / Redux)',
    tagline: 'State outside the React tree.',
    summary: 'Subscribe with selectors, compare Zustand vs Redux, and animate unidirectional data flow.',
    group: 'react',
    minutes: 8,
    modelTitle: 'External stores',
    hasPlayground: true,
    playgroundTitle: 'Store & selector labs',
    hasHood: true,
  }),
  chapterMeta({
    id: 'react-store-choosing',
    title: 'Choosing state placement',
    tagline: 'Local, Context, store, or server cache?',
    summary: 'Pick the simplest state tool — useState, lift, Context, Zustand/Redux, or TanStack Query.',
    group: 'react',
    minutes: 5,
    modelTitle: 'Decision framework',
    hasPlayground: true,
    playgroundTitle: 'State chooser quiz',
  }),
  chapterMeta({
    id: 'react-lab-counter',
    title: 'Lab: counter & state',
    tagline: 'Live useState demo.',
    summary: 'Increment and decrement a counter to see useState and re-renders in action.',
    group: 'react',
    minutes: 4,
    modelTitle: 'How the counter works',
    hasPlayground: true,
    playgroundTitle: 'Counter lab',
  }),
  chapterMeta({
    id: 'react-lab-props',
    title: 'Lab: props playground',
    tagline: 'Edit props and watch the child update.',
    summary: 'Change name and role inputs and see props flow into a Greeting card.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Props in practice',
    hasPlayground: true,
    playgroundTitle: 'Props lab',
  }),
  chapterMeta({
    id: 'react-lab-lists',
    title: 'Lab: todo list',
    tagline: 'Lists, keys, and immutable toggles.',
    summary: 'Add todos and toggle checkboxes with immutable array updates.',
    group: 'react',
    minutes: 5,
    modelTitle: 'List updates',
    hasPlayground: true,
    playgroundTitle: 'Todo list lab',
  }),
  chapterMeta({
    id: 'react-hood-vdom',
    title: 'Virtual DOM & reconciliation',
    tagline: 'How React updates the page efficiently.',
    summary: 'Render, reconcile, and commit — keys, Fiber, React.memo, and why index keys break lists.',
    group: 'react',
    minutes: 8,
    modelTitle: 'Virtual DOM & reconciliation',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Reconciliation labs',
  }),
  chapterMeta({
    id: 'react-hood-hooks',
    title: 'Rules of hooks',
    tagline: 'Top-level calls only.',
    summary: 'Hook slots, call order, custom hooks, eslint rules, and five common violations.',
    group: 'react',
    minutes: 7,
    modelTitle: 'Rules of hooks',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Hook rules labs',
  }),
  chapterMeta({
    id: 'react-hood-stack',
    title: 'React ecosystem',
    tagline: 'Router, data fetching, and build tools.',
    summary: 'Full-stack flow from Vite to TanStack Query to FastAPI — SPA vs SSR and tool roles.',
    group: 'react',
    minutes: 7,
    modelTitle: 'Ecosystem & full stack',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Stack & ecosystem labs',
  }),
]
