import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const reactLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'react-intro',
    title: 'Why React',
    tagline: 'UI = f(state) — building interfaces from components.',
    summary: 'Learn why React models UI as a function of state and how components compose into pages.',
    group: 'react',
    minutes: 4,
    modelTitle: 'UI as a function of state',
    hasPlayground: true,
    playgroundTitle: 'See UI = f(state)',
  }),
  chapterMeta({
    id: 'react-jsx-basics',
    title: 'Components & JSX',
    tagline: 'Functions that return HTML-like syntax.',
    summary: 'Write React components that return JSX and compose them like HTML tags.',
    group: 'react',
    minutes: 5,
    modelTitle: 'Components & JSX',
    hasPlayground: true,
    playgroundTitle: 'Compose components',
  }),
  chapterMeta({
    id: 'react-jsx-rules',
    title: 'JSX syntax rules',
    tagline: 'className, fragments, and curly-brace expressions.',
    summary: 'Master JSX differences from HTML: fragments, className, self-closing tags, and expressions.',
    group: 'react',
    minutes: 4,
    modelTitle: 'JSX syntax rules',
    hasPlayground: true,
    playgroundTitle: 'Fix JSX mistakes',
  }),
  chapterMeta({
    id: 'react-props',
    title: 'Props: data flows down',
    tagline: 'Read-only inputs from parent to child.',
    summary: 'Pass data into components via props — like function arguments for UI.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Props',
    hasPlayground: true,
    playgroundTitle: 'Props lab',
  }),
  chapterMeta({
    id: 'react-state',
    title: 'State with useState',
    tagline: 'Memory between renders.',
    summary: 'Use useState to remember values and trigger re-renders when they change.',
    group: 'react',
    minutes: 5,
    modelTitle: 'useState',
    hasPlayground: true,
    playgroundTitle: 'Counter lab',
  }),
  chapterMeta({
    id: 'react-events',
    title: 'Event handlers',
    tagline: 'onClick, onChange, and synthetic events.',
    summary: 'Wire user interactions to state setters with camelCase event props.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Event handlers',
    hasPlayground: true,
    playgroundTitle: 'Events lab',
  }),
  chapterMeta({
    id: 'react-lists',
    title: 'Lists & keys',
    tagline: 'map(), stable keys, and immutable updates.',
    summary: 'Render collections with .map(), assign stable keys, and update arrays immutably.',
    group: 'react',
    minutes: 5,
    modelTitle: 'Lists & keys',
    hasPlayground: true,
    playgroundTitle: 'Todo list lab',
  }),
  chapterMeta({
    id: 'react-effects',
    title: 'Side effects with useEffect',
    tagline: 'Fetch, subscribe, and sync after render.',
    summary: 'Run side effects after render with useEffect and control re-runs via the dependency array.',
    group: 'react',
    minutes: 5,
    modelTitle: 'useEffect',
    hasPlayground: true,
    playgroundTitle: 'Effects lab',
  }),
  chapterMeta({
    id: 'react-store-lift',
    title: 'Prop drilling & lifting state',
    tagline: 'When local state is not enough.',
    summary: 'Recognize prop drilling and lift shared state to a common ancestor.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Lifting state',
    hasPlayground: true,
    playgroundTitle: 'Lift state lab',
  }),
  chapterMeta({
    id: 'react-store-context',
    title: 'Context API',
    tagline: 'Share values without threading props.',
    summary: 'Provide data at the top of a tree and read it anywhere below with Context.',
    group: 'react',
    minutes: 6,
    modelTitle: 'Context API',
    hasPlayground: true,
    playgroundTitle: 'Profile demo',
  }),
  chapterMeta({
    id: 'react-store-external',
    title: 'External stores (Zustand / Redux)',
    tagline: 'State outside the React tree.',
    summary: 'Subscribe components to external stores when many branches need the same fast-updating data.',
    group: 'react',
    minutes: 6,
    modelTitle: 'External stores',
    hasPlayground: true,
    playgroundTitle: 'Cart store demo',
    hasHood: true,
  }),
  chapterMeta({
    id: 'react-lab-counter',
    title: 'Lab: counter & state',
    tagline: 'Live useState demo.',
    summary: 'Increment and decrement a counter to see useState and re-renders in action.',
    group: 'react',
    minutes: 4,
    modelTitle: 'How the counter works',
    hasPlayground: true,
    playgroundTitle: 'Counter lab',
  }),
  chapterMeta({
    id: 'react-lab-props',
    title: 'Lab: props playground',
    tagline: 'Edit props and watch the child update.',
    summary: 'Change name and role inputs and see props flow into a Greeting card.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Props in practice',
    hasPlayground: true,
    playgroundTitle: 'Props lab',
  }),
  chapterMeta({
    id: 'react-lab-lists',
    title: 'Lab: todo list',
    tagline: 'Lists, keys, and immutable toggles.',
    summary: 'Add todos and toggle checkboxes with immutable array updates.',
    group: 'react',
    minutes: 5,
    modelTitle: 'List updates',
    hasPlayground: true,
    playgroundTitle: 'Todo list lab',
  }),
  chapterMeta({
    id: 'react-hood-vdom',
    title: 'Virtual DOM & reconciliation',
    tagline: 'How React updates the page efficiently.',
    summary: 'Understand the virtual DOM, diffing, and minimal DOM updates.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Overview',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Reconciliation demo',
  }),
  chapterMeta({
    id: 'react-hood-hooks',
    title: 'Rules of hooks',
    tagline: 'Top-level calls only.',
    summary: 'Learn why hooks must run in a consistent order at the top level of components.',
    group: 'react',
    minutes: 3,
    modelTitle: 'Hook rules',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Hook rules lab',
  }),
  chapterMeta({
    id: 'react-hood-stack',
    title: 'React ecosystem',
    tagline: 'Router, data fetching, and build tools.',
    summary: 'See how React fits with routers, TanStack Query, TypeScript, and FastAPI backends.',
    group: 'react',
    minutes: 4,
    modelTitle: 'Beyond the core library',
    hasHood: true,
    hasPlayground: true,
    playgroundTitle: 'Ecosystem map',
  }),
]
