import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const cssLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'css-intro',
    title: 'Why CSS feels hard',
    tagline: 'Cascade, inheritance, and invisible layout rules.',
    summary: 'Understand why small CSS changes have big effects — the cascade, inheritance, and why devtools are your best friend.',
    group: 'css',
    minutes: 5,
    modelTitle: 'The mental model',
    hasPlayground: true,
    playgroundTitle: 'Cascade & inheritance lab',
  }),
  chapterMeta({
    id: 'css-box-model',
    title: 'The box model',
    tagline: 'Content, padding, border, margin — and box-sizing.',
    summary: 'Learn what width actually means, why buttons look bigger than expected, and why border-box is the default fix.',
    group: 'css',
    minutes: 6,
    modelTitle: 'Boxes all the way down',
    hasPlayground: true,
    playgroundTitle: 'Resize the box live',
  }),
  chapterMeta({
    id: 'css-layout',
    title: 'Layout with Flex & Grid',
    tagline: 'Rows, columns, and alignment without float hacks.',
    summary: 'Use Flexbox for one-dimensional layouts and Grid for two-dimensional pages — the modern replacement for fragile float tricks.',
    group: 'css',
    minutes: 7,
    modelTitle: 'Flex & Grid',
    hasPlayground: true,
    playgroundTitle: 'Flex layout lab',
  }),
  chapterMeta({
    id: 'css-position',
    title: 'Position & stacking',
    tagline: 'static, relative, absolute, fixed, sticky — and z-index.',
    summary: 'Control where elements sit on the page, anchor dropdowns to parents, and understand why z-index sometimes does nothing.',
    group: 'css',
    minutes: 6,
    modelTitle: 'Position modes',
    hasPlayground: true,
    playgroundTitle: 'Position lab',
  }),
  chapterMeta({
    id: 'css-overflow',
    title: 'Overflow & scrolling',
    tagline: 'When content escapes its box — hidden, scroll, or clip.',
    summary: 'Learn overflow: visible, hidden, scroll, and auto — and fix the classic “layout blew up” sidebar and table bugs.',
    group: 'css',
    minutes: 5,
    modelTitle: 'Overflow modes',
    hasPlayground: true,
    playgroundTitle: 'Overflow lab',
  }),
  chapterMeta({
    id: 'css-themes',
    title: 'Themes & CSS variables',
    tagline: 'Custom properties, dark mode, and one palette everywhere.',
    summary: 'Use CSS variables for colors and spacing, wire dark/light themes with data attributes, and avoid hard-coded hex in every component.',
    group: 'css',
    minutes: 6,
    modelTitle: 'Variables & themes',
    hasPlayground: true,
    playgroundTitle: 'Theme tokens lab',
  }),
  chapterMeta({
    id: 'css-cascade',
    title: 'Cascade & specificity',
    tagline: 'Which rule wins — and why !important is a last resort.',
    summary: 'Read specificity scores, understand inheritance, and stop fighting the cascade with random overrides.',
    group: 'css',
    minutes: 5,
    modelTitle: 'Specificity & inheritance',
    hasPlayground: true,
    playgroundTitle: 'Specificity calculator',
  }),
  chapterMeta({
    id: 'css-hacks',
    title: 'Hacks vs proper fixes',
    tagline: 'Centering, margin collapse, z-index wars, and what to do instead.',
    summary: 'Recognize classic CSS hacks (float clears, magic numbers, !important sprawl) and replace them with flex, grid, and border-box.',
    group: 'css',
    minutes: 6,
    modelTitle: 'Common pitfalls',
    hasPlayground: true,
    playgroundTitle: 'Hack vs fix lab',
    hasHood: true,
  }),
]
