import { chapterMeta } from '../chapterMeta.ts'
import type { LessonMeta } from '../meta.ts'

export const fastapiLessonsMeta: LessonMeta[] = [
  chapterMeta({
    id: 'fastapi-intro',
    title: 'Why FastAPI',
    tagline: 'Modern Python APIs with validation and auto-docs.',
    summary: 'See why FastAPI pairs type hints, Pydantic, and OpenAPI for less boilerplate.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'Why FastAPI',
  }),
  chapterMeta({
    id: 'fastapi-routes-basics',
    title: 'GET routes & JSON responses',
    tagline: 'Map paths to Python functions.',
    summary: 'Define @app.get handlers that return JSON-serializable dicts and lists.',
    group: 'fastapi',
    minutes: 5,
    modelTitle: 'GET routes',
    hasPlayground: true,
    playgroundTitle: 'Route handlers lab',
  }),
  chapterMeta({
    id: 'fastapi-routes-crud',
    title: 'POST, PUT & DELETE',
    tagline: 'REST verbs for create, update, and delete.',
    summary: 'Use POST, PUT/PATCH, and DELETE with appropriate status codes like 201 and 204.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'CRUD routes',
  }),
  chapterMeta({
    id: 'fastapi-models-request',
    title: 'Request models (Pydantic)',
    tagline: 'Validate JSON bodies before your handler runs.',
    summary: 'Declare Pydantic models for POST/PUT bodies and get 422 errors for free.',
    group: 'fastapi',
    minutes: 5,
    modelTitle: 'Request models',
    hasPlayground: true,
    playgroundTitle: 'Validation lab',
  }),
  chapterMeta({
    id: 'fastapi-models-response',
    title: 'Response models & status codes',
    tagline: 'Document and filter API output.',
    summary: 'Use response_model to shape outgoing JSON and document responses in OpenAPI.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'Response models',
  }),
  chapterMeta({
    id: 'fastapi-params-path',
    title: 'Path parameters',
    tagline: 'Typed segments from the URL.',
    summary: 'Bind URL segments like /users/{id} to typed function parameters.',
    group: 'fastapi',
    minutes: 3,
    modelTitle: 'Path parameters',
  }),
  chapterMeta({
    id: 'fastapi-params-query',
    title: 'Query parameters',
    tagline: 'Filters and pagination from ?q=…',
    summary: 'Parse query strings into function parameters with defaults.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'Query parameters',
    hasPlayground: true,
    playgroundTitle: 'Search lab',
  }),
  chapterMeta({
    id: 'fastapi-params-body',
    title: 'Request body',
    tagline: 'JSON payloads on POST and PUT.',
    summary: 'Combine a Pydantic body model with path and query params in one handler.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'Request body',
  }),
  chapterMeta({
    id: 'fastapi-deps-database',
    title: 'Database dependencies',
    tagline: 'Inject DB sessions with Depends.',
    summary: 'Share database setup via dependencies and override them in tests.',
    group: 'fastapi',
    minutes: 5,
    modelTitle: 'Database dependencies',
    hasPlayground: true,
    playgroundTitle: 'Dependency injection lab',
    hasHood: true,
  }),
  chapterMeta({
    id: 'fastapi-deps-auth',
    title: 'Auth dependencies',
    tagline: 'Bearer tokens and get_current_user.',
    summary: 'Validate auth before handlers run using Depends and HTTPException(401).',
    group: 'fastapi',
    minutes: 5,
    modelTitle: 'Auth dependencies',
    hasPlayground: true,
    playgroundTitle: 'Auth lab',
  }),
  chapterMeta({
    id: 'fastapi-errors',
    title: 'Errors & HTTPException',
    tagline: 'Clear failures with the right status code.',
    summary: 'Raise HTTPException for expected errors like 404 and 400.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'HTTPException',
    hasPlayground: true,
    playgroundTitle: 'Error handling lab',
  }),
  chapterMeta({
    id: 'fastapi-hood-asgi',
    title: 'ASGI & async handlers',
    tagline: 'Non-blocking I/O with async def.',
    summary: 'Use async handlers when awaiting database or HTTP calls under ASGI.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'Async handlers',
    hasPlayground: true,
    playgroundTitle: 'Async lab',
  }),
  chapterMeta({
    id: 'fastapi-hood-openapi',
    title: 'OpenAPI & /docs',
    tagline: 'Interactive API docs from type hints.',
    summary: 'Explore auto-generated Swagger UI at /docs and ReDoc at /redoc.',
    group: 'fastapi',
    minutes: 3,
    modelTitle: 'OpenAPI docs',
  }),
  chapterMeta({
    id: 'fastapi-hood-cors',
    title: 'CORS & React integration',
    tagline: 'Let your frontend call the API from another origin.',
    summary: 'Configure CORSMiddleware so a Vite React app can fetch localhost:8000.',
    group: 'fastapi',
    minutes: 4,
    modelTitle: 'CORS',
    hasPlayground: true,
    playgroundTitle: 'CORS simulation',
  }),
  chapterMeta({
    id: 'fastapi-hood-stack',
    title: 'Full-stack stack',
    tagline: 'React → FastAPI → database.',
    summary: 'See how a typical app connects React UI, FastAPI JSON APIs, and persistence.',
    group: 'fastapi',
    minutes: 3,
    modelTitle: 'Architecture',
    hasHood: true,
  }),
]
